<?php
	/**
	 * Created by Chris.
	 * Title: oop
	 * Date: 04/12/2017
	 * Time: 17:11
	 */
	
	use Philo\Blade\Blade;
	
	/**
	 * Redirects
	 *
	 * @param $redirect
	 */
	function redirect( $redirect )
	{
		
		header( "Location: {$redirect}" );
		
	}
	
	/**
	 * Returns showcase ID from URL
	 *
	 * @return null|int
	 */
	function showcaseUriID()
	{
		
		$splitUri = explode( '/' , $_SERVER[ 'REQUEST_URI' ] );
		
		switch ( $splitUri[ 2 ] )
		{
			case 'showcase':
				
				return (int) $splitUri[ 3 ];
				break;
			
			default:
				
				return null;
				break;
		}
		
	}
	
	/**
	 * Bytes to KB to MB to GB conversion
	 *
	 * @param $bytes
	 *
	 * @return string
	 */
	function formatSizeUnits( $bytes )
	{
		
		if ( $bytes >= 1073741824 )
		{
			$bytes = number_format( $bytes / 1073741824 , 2 ) . ' GB';
		}
		elseif ( $bytes >= 1048576 )
		{
			$bytes = number_format( $bytes / 1048576 , 2 ) . ' MB';
		}
		elseif ( $bytes >= 1024 )
		{
			$bytes = number_format( $bytes / 1024 , 2 ) . ' KB';
		}
		elseif ( $bytes > 1 )
		{
			$bytes = $bytes . ' bytes';
		}
		elseif ( $bytes == 1 )
		{
			$bytes = $bytes . ' byte';
		}
		else
		{
			$bytes = '0 bytes';
		}
		
		return $bytes;
	}
	
	/**
	 * Front View
	 *
	 * @param       $path
	 * @param array $data
	 */
	function view( $path , array $data = [] )
	{
		
		// Laravel-Blade
		$views = SITE_ROOT . 'display/front/view';
		$cache = SITE_ROOT . 'display/front/cache';
		
		$blade = new Blade( $views , $cache );
		echo $blade->view()->make( $path , $data )->render();
	}
	
	/**
	 * Admin View
	 *
	 * @param       $path
	 * @param array $data
	 */
	function adminView( $path , array $data = [] )
	{
		
		// Laravel-Blade
		$views = SITE_ROOT . 'display/sc-panel/view';
		$cache = SITE_ROOT . 'display/sc-panel/cache';
		
		$restricted = [
			'statistics' ,
			'general_settings' ,
			'email_settings' ,
			'social_settings' ,
			'users' ,
			'promotions'
		];
		
		$blade = new Blade( $views , $cache );
		
		if ( ! isAdmin() )
		{
			if ( ! in_array( $path , $restricted , true ) )
			{
				echo $blade->view()->make( $path , $data )->render();
			}
		}
		else
		{
			echo $blade->view()->make( $path , $data )->render();
		}
	}
	
	/**
	 * Check if use has administrative permissions
	 *
	 * @return bool
	 */
	function isAdmin()
	{
		
		return ( isset( \Classes\Core\Session::instance()->user_id ) && ! empty( \Classes\Core\User::find_by_id( \Classes\Core\Session::instance()->user_id )->privilege ) ) ? true : false;
	}
	
	/**
	 * Return Root URL
	 *
	 * @param bool $encode // encode special characters
	 */
	function sca_base_url( $encode = true )
	{
		
		$url = ( isset( $_SERVER[ 'HTTPS' ] ) ? 'https' : 'http' ) . '://' . $_SERVER[ 'HTTP_HOST' ] . '/';
		
		if ( $encode )
		{
			htmlspecialchars( $url , ENT_QUOTES , 'UTF-8' );
		}
		
		echo strtolower( $url );
	}
	
	/**
	 * Return if empty else empty string
	 *
	 * @param $input
	 *
	 * @return string
	 */
	function notEmpty( $input )
	{
		
		return ! empty( $input ) ? $input : '';
	}
	
	/**
	 * Checks if value is empty but zero will return false
	 *
	 * @param $var
	 *
	 * @return bool
	 */
	function isEmpty( $var )
	{
		
		if ( is_numeric( $var ) )
		{
			return false;
		}
		elseif ( empty( $var ) )
		{
			return true;
		}
		else
		{
			return false;
		}
	}
	
	/**
	 * Strips all other tags other than which are allowed
	 *
	 * @param $input
	 *
	 * @return string
	 */
	function allowedTags( $input )
	{
		
		return strip_tags( $input , '<ul><ol><li><p><h3><h4><h5><strong><em><i><a>' );
	}
	
	/**
	 *  replace spaces with underscores for pretty urls
	 *
	 * @param $input
	 *
	 * @return null|string|string[]
	 */
	function urlString( $input )
	{
		
		return preg_replace( '/\s/' , '_' , strtolower( $input ) );
	}
	
	/**
	 * Trim string from start to limits end
	 *
	 * @param $trimMe
	 * @param $limit
	 *
	 * @return bool|string
	 */
	function trimString( $trimMe , $limit )
	{
		
		return substr( $trimMe , 0 , $limit );
		
	}
	
	/**
	 * Catches all exceptions
	 *
	 * @param $e
	 */
	function exceptionCatcher( $e )
	{
		
		
		if ( $e->getCode() === 1044 )
		{
			$returnMessage = 'Invalid database name';
		}
		elseif ( $e->getCode() === 1045 )
		{
			$returnMessage = 'Invalid database username or password';
		}
		elseif ( $e->getCode() === 1050 )
		{
			$returnMessage = 'Base table or view already exists';
		}
		elseif ( $e->getCode() === 1146 )
		{
			$returnMessage = 'Base table or view not found';
		}
		else
		{
			
			if ( sca_get_preference( 'showcase' , 'sca_errorlogging' ) )
			{
				
				$logging = new \Classes\Core\Logging();
				
				$logging->logs       = "<strong>Exception : </strong>" . $e->getMessage() . '<br><strong>Exception Code: </strong>' . $e->getCode();
				$logging->created_at = date( "Y-m-d H:i:s" );
				$logging->create();
			}
			
			$returnMessage = "<strong>Error Notice : </strong> something went wrong contact site admin";
		}
		
		echo $returnMessage;
	}
	
	/**
	 * Echos CSRFToken
	 *
	 * @throws \Exception
	 */
	function echoCSRFInput()
	{
		
		echo '<input type="hidden" name="CSRFToken" id="CSRFToken" value="' . \Classes\Core\CSRFToken::_SetToken() . '" />';
	}
	
	/**
	 * returns CSRFToken
	 *
	 * @return string
	 * @throws \Exception
	 */
	function returnCSRFInput()
	{
		
		return '<input type="hidden" name="CSRFToken" id="CSRFToken" value="' . \Classes\Core\CSRFToken::_SetToken() . '" />';
	}
	
	/**
	 * Echos scripts
	 */
	function loadScripts()
	{
		
		$stripePubKey = ( sca_get_preference( 'showcase' , 'sca_stripe_mode' ) ) ? sca_get_preference( 'showcase' , 'sca_livePubKey' ) : sca_get_preference( 'showcase' , 'sca_testPubKey' );
		$script       = '<script>var stripePubKey = "' . $stripePubKey . '"</script>';
		$script       .= '<script src="https://js.stripe.com/v3/"></script>';
		$script       .= '<script src="' . sca_get_preference( 'showcase' , 'sca_siteurl' ) . 'resources/assets/js/bundle.js" type="text/javascript"></script>';
		
		echo $script;
	}
	
	/**
	 * Returns timezones in a select list
	 * Takes 2 parameters
	 *
	 * @param $formName  // form name and id
	 * @param $valueHolder // When matched select in list
	 *
	 * @return string
	 */
	function returnTimezoneSelect( $formName , $valueHolder)
	{
		
		// Array of timezones
		$timezones = array(
			'America/Adak'              => '(GMT-10:00) America/Adak (Hawaii-Aleutian Standard Time)' ,
			'America/Atka'              => '(GMT-10:00) America/Atka (Hawaii-Aleutian Standard Time)' ,
			'America/Anchorage'         => '(GMT-9:00) America/Anchorage (Alaska Standard Time)' ,
			'America/Juneau'            => '(GMT-9:00) America/Juneau (Alaska Standard Time)' ,
			'America/Nome'              => '(GMT-9:00) America/Nome (Alaska Standard Time)' ,
			'America/Yakutat'           => '(GMT-9:00) America/Yakutat (Alaska Standard Time)' ,
			'America/Dawson'            => '(GMT-8:00) America/Dawson (Pacific Standard Time)' ,
			'America/Ensenada'          => '(GMT-8:00) America/Ensenada (Pacific Standard Time)' ,
			'America/Los_Angeles'       => '(GMT-8:00) America/Los_Angeles (Pacific Standard Time)' ,
			'America/Tijuana'           => '(GMT-8:00) America/Tijuana (Pacific Standard Time)' ,
			'America/Vancouver'         => '(GMT-8:00) America/Vancouver (Pacific Standard Time)' ,
			'America/Whitehorse'        => '(GMT-8:00) America/Whitehorse (Pacific Standard Time)' ,
			'Canada/Pacific'            => '(GMT-8:00) Canada/Pacific (Pacific Standard Time)' ,
			'Canada/Yukon'              => '(GMT-8:00) Canada/Yukon (Pacific Standard Time)' ,
			'Mexico/BajaNorte'          => '(GMT-8:00) Mexico/BajaNorte (Pacific Standard Time)' ,
			'America/Boise'             => '(GMT-7:00) America/Boise (Mountain Standard Time)' ,
			'America/Cambridge_Bay'     => '(GMT-7:00) America/Cambridge_Bay (Mountain Standard Time)' ,
			'America/Chihuahua'         => '(GMT-7:00) America/Chihuahua (Mountain Standard Time)' ,
			'America/Dawson_Creek'      => '(GMT-7:00) America/Dawson_Creek (Mountain Standard Time)' ,
			'America/Denver'            => '(GMT-7:00) America/Denver (Mountain Standard Time)' ,
			'America/Edmonton'          => '(GMT-7:00) America/Edmonton (Mountain Standard Time)' ,
			'America/Hermosillo'        => '(GMT-7:00) America/Hermosillo (Mountain Standard Time)' ,
			'America/Inuvik'            => '(GMT-7:00) America/Inuvik (Mountain Standard Time)' ,
			'America/Mazatlan'          => '(GMT-7:00) America/Mazatlan (Mountain Standard Time)' ,
			'America/Phoenix'           => '(GMT-7:00) America/Phoenix (Mountain Standard Time)' ,
			'America/Shiprock'          => '(GMT-7:00) America/Shiprock (Mountain Standard Time)' ,
			'America/Yellowknife'       => '(GMT-7:00) America/Yellowknife (Mountain Standard Time)' ,
			'Canada/Mountain'           => '(GMT-7:00) Canada/Mountain (Mountain Standard Time)' ,
			'Mexico/BajaSur'            => '(GMT-7:00) Mexico/BajaSur (Mountain Standard Time)' ,
			'America/Belize'            => '(GMT-6:00) America/Belize (Central Standard Time)' ,
			'America/Cancun'            => '(GMT-6:00) America/Cancun (Central Standard Time)' ,
			'America/Chicago'           => '(GMT-6:00) America/Chicago (Central Standard Time)' ,
			'America/Costa_Rica'        => '(GMT-6:00) America/Costa_Rica (Central Standard Time)' ,
			'America/El_Salvador'       => '(GMT-6:00) America/El_Salvador (Central Standard Time)' ,
			'America/Guatemala'         => '(GMT-6:00) America/Guatemala (Central Standard Time)' ,
			'America/Knox_IN'           => '(GMT-6:00) America/Knox_IN (Central Standard Time)' ,
			'America/Managua'           => '(GMT-6:00) America/Managua (Central Standard Time)' ,
			'America/Menominee'         => '(GMT-6:00) America/Menominee (Central Standard Time)' ,
			'America/Merida'            => '(GMT-6:00) America/Merida (Central Standard Time)' ,
			'America/Mexico_City'       => '(GMT-6:00) America/Mexico_City (Central Standard Time)' ,
			'America/Monterrey'         => '(GMT-6:00) America/Monterrey (Central Standard Time)' ,
			'America/Rainy_River'       => '(GMT-6:00) America/Rainy_River (Central Standard Time)' ,
			'America/Rankin_Inlet'      => '(GMT-6:00) America/Rankin_Inlet (Central Standard Time)' ,
			'America/Regina'            => '(GMT-6:00) America/Regina (Central Standard Time)' ,
			'America/Swift_Current'     => '(GMT-6:00) America/Swift_Current (Central Standard Time)' ,
			'America/Tegucigalpa'       => '(GMT-6:00) America/Tegucigalpa (Central Standard Time)' ,
			'America/Winnipeg'          => '(GMT-6:00) America/Winnipeg (Central Standard Time)' ,
			'Canada/Central'            => '(GMT-6:00) Canada/Central (Central Standard Time)' ,
			'Canada/East-Saskatchewan'  => '(GMT-6:00) Canada/East-Saskatchewan (Central Standard Time)' ,
			'Canada/Saskatchewan'       => '(GMT-6:00) Canada/Saskatchewan (Central Standard Time)' ,
			'Chile/EasterIsland'        => '(GMT-6:00) Chile/EasterIsland (Easter Is. Time)' ,
			'Mexico/General'            => '(GMT-6:00) Mexico/General (Central Standard Time)' ,
			'America/Atikokan'          => '(GMT-5:00) America/Atikokan (Eastern Standard Time)' ,
			'America/Bogota'            => '(GMT-5:00) America/Bogota (Colombia Time)' ,
			'America/Cayman'            => '(GMT-5:00) America/Cayman (Eastern Standard Time)' ,
			'America/Coral_Harbour'     => '(GMT-5:00) America/Coral_Harbour (Eastern Standard Time)' ,
			'America/Detroit'           => '(GMT-5:00) America/Detroit (Eastern Standard Time)' ,
			'America/Fort_Wayne'        => '(GMT-5:00) America/Fort_Wayne (Eastern Standard Time)' ,
			'America/Grand_Turk'        => '(GMT-5:00) America/Grand_Turk (Eastern Standard Time)' ,
			'America/Guayaquil'         => '(GMT-5:00) America/Guayaquil (Ecuador Time)' ,
			'America/Havana'            => '(GMT-5:00) America/Havana (Cuba Standard Time)' ,
			'America/Indianapolis'      => '(GMT-5:00) America/Indianapolis (Eastern Standard Time)' ,
			'America/Iqaluit'           => '(GMT-5:00) America/Iqaluit (Eastern Standard Time)' ,
			'America/Jamaica'           => '(GMT-5:00) America/Jamaica (Eastern Standard Time)' ,
			'America/Lima'              => '(GMT-5:00) America/Lima (Peru Time)' ,
			'America/Louisville'        => '(GMT-5:00) America/Louisville (Eastern Standard Time)' ,
			'America/Montreal'          => '(GMT-5:00) America/Montreal (Eastern Standard Time)' ,
			'America/Nassau'            => '(GMT-5:00) America/Nassau (Eastern Standard Time)' ,
			'America/New_York'          => '(GMT-5:00) America/New_York (Eastern Standard Time)' ,
			'America/Nipigon'           => '(GMT-5:00) America/Nipigon (Eastern Standard Time)' ,
			'America/Panama'            => '(GMT-5:00) America/Panama (Eastern Standard Time)' ,
			'America/Pangnirtung'       => '(GMT-5:00) America/Pangnirtung (Eastern Standard Time)' ,
			'America/Port-au-Prince'    => '(GMT-5:00) America/Port-au-Prince (Eastern Standard Time)' ,
			'America/Resolute'          => '(GMT-5:00) America/Resolute (Eastern Standard Time)' ,
			'America/Thunder_Bay'       => '(GMT-5:00) America/Thunder_Bay (Eastern Standard Time)' ,
			'America/Toronto'           => '(GMT-5:00) America/Toronto (Eastern Standard Time)' ,
			'Canada/Eastern'            => '(GMT-5:00) Canada/Eastern (Eastern Standard Time)' ,
			'America/Caracas'           => '(GMT-4:-30) America/Caracas (Venezuela Time)' ,
			'America/Anguilla'          => '(GMT-4:00) America/Anguilla (Atlantic Standard Time)' ,
			'America/Antigua'           => '(GMT-4:00) America/Antigua (Atlantic Standard Time)' ,
			'America/Aruba'             => '(GMT-4:00) America/Aruba (Atlantic Standard Time)' ,
			'America/Asuncion'          => '(GMT-4:00) America/Asuncion (Paraguay Time)' ,
			'America/Barbados'          => '(GMT-4:00) America/Barbados (Atlantic Standard Time)' ,
			'America/Blanc-Sablon'      => '(GMT-4:00) America/Blanc-Sablon (Atlantic Standard Time)' ,
			'America/Boa_Vista'         => '(GMT-4:00) America/Boa_Vista (Amazon Time)' ,
			'America/Campo_Grande'      => '(GMT-4:00) America/Campo_Grande (Amazon Time)' ,
			'America/Cuiaba'            => '(GMT-4:00) America/Cuiaba (Amazon Time)' ,
			'America/Curacao'           => '(GMT-4:00) America/Curacao (Atlantic Standard Time)' ,
			'America/Dominica'          => '(GMT-4:00) America/Dominica (Atlantic Standard Time)' ,
			'America/Eirunepe'          => '(GMT-4:00) America/Eirunepe (Amazon Time)' ,
			'America/Glace_Bay'         => '(GMT-4:00) America/Glace_Bay (Atlantic Standard Time)' ,
			'America/Goose_Bay'         => '(GMT-4:00) America/Goose_Bay (Atlantic Standard Time)' ,
			'America/Grenada'           => '(GMT-4:00) America/Grenada (Atlantic Standard Time)' ,
			'America/Guadeloupe'        => '(GMT-4:00) America/Guadeloupe (Atlantic Standard Time)' ,
			'America/Guyana'            => '(GMT-4:00) America/Guyana (Guyana Time)' ,
			'America/Halifax'           => '(GMT-4:00) America/Halifax (Atlantic Standard Time)' ,
			'America/La_Paz'            => '(GMT-4:00) America/La_Paz (Bolivia Time)' ,
			'America/Manaus'            => '(GMT-4:00) America/Manaus (Amazon Time)' ,
			'America/Marigot'           => '(GMT-4:00) America/Marigot (Atlantic Standard Time)' ,
			'America/Martinique'        => '(GMT-4:00) America/Martinique (Atlantic Standard Time)' ,
			'America/Moncton'           => '(GMT-4:00) America/Moncton (Atlantic Standard Time)' ,
			'America/Montserrat'        => '(GMT-4:00) America/Montserrat (Atlantic Standard Time)' ,
			'America/Port_of_Spain'     => '(GMT-4:00) America/Port_of_Spain (Atlantic Standard Time)' ,
			'America/Porto_Acre'        => '(GMT-4:00) America/Porto_Acre (Amazon Time)' ,
			'America/Porto_Velho'       => '(GMT-4:00) America/Porto_Velho (Amazon Time)' ,
			'America/Puerto_Rico'       => '(GMT-4:00) America/Puerto_Rico (Atlantic Standard Time)' ,
			'America/Rio_Branco'        => '(GMT-4:00) America/Rio_Branco (Amazon Time)' ,
			'America/Santiago'          => '(GMT-4:00) America/Santiago (Chile Time)' ,
			'America/Santo_Domingo'     => '(GMT-4:00) America/Santo_Domingo (Atlantic Standard Time)' ,
			'America/St_Barthelemy'     => '(GMT-4:00) America/St_Barthelemy (Atlantic Standard Time)' ,
			'America/St_Kitts'          => '(GMT-4:00) America/St_Kitts (Atlantic Standard Time)' ,
			'America/St_Lucia'          => '(GMT-4:00) America/St_Lucia (Atlantic Standard Time)' ,
			'America/St_Thomas'         => '(GMT-4:00) America/St_Thomas (Atlantic Standard Time)' ,
			'America/St_Vincent'        => '(GMT-4:00) America/St_Vincent (Atlantic Standard Time)' ,
			'America/Thule'             => '(GMT-4:00) America/Thule (Atlantic Standard Time)' ,
			'America/Tortola'           => '(GMT-4:00) America/Tortola (Atlantic Standard Time)' ,
			'America/Virgin'            => '(GMT-4:00) America/Virgin (Atlantic Standard Time)' ,
			'Antarctica/Palmer'         => '(GMT-4:00) Antarctica/Palmer (Chile Time)' ,
			'Atlantic/Bermuda'          => '(GMT-4:00) Atlantic/Bermuda (Atlantic Standard Time)' ,
			'Atlantic/Stanley'          => '(GMT-4:00) Atlantic/Stanley (Falkland Is. Time)' ,
			'Brazil/Acre'               => '(GMT-4:00) Brazil/Acre (Amazon Time)' ,
			'Brazil/West'               => '(GMT-4:00) Brazil/West (Amazon Time)' ,
			'Canada/Atlantic'           => '(GMT-4:00) Canada/Atlantic (Atlantic Standard Time)' ,
			'Chile/Continental'         => '(GMT-4:00) Chile/Continental (Chile Time)' ,
			'America/St_Johns'          => '(GMT-3:-30) America/St_Johns (Newfoundland Standard Time)' ,
			'Canada/Newfoundland'       => '(GMT-3:-30) Canada/Newfoundland (Newfoundland Standard Time)' ,
			'America/Araguaina'         => '(GMT-3:00) America/Araguaina (Brasilia Time)' ,
			'America/Bahia'             => '(GMT-3:00) America/Bahia (Brasilia Time)' ,
			'America/Belem'             => '(GMT-3:00) America/Belem (Brasilia Time)' ,
			'America/Buenos_Aires'      => '(GMT-3:00) America/Buenos_Aires (Argentine Time)' ,
			'America/Catamarca'         => '(GMT-3:00) America/Catamarca (Argentine Time)' ,
			'America/Cayenne'           => '(GMT-3:00) America/Cayenne (French Guiana Time)' ,
			'America/Cordoba'           => '(GMT-3:00) America/Cordoba (Argentine Time)' ,
			'America/Fortaleza'         => '(GMT-3:00) America/Fortaleza (Brasilia Time)' ,
			'America/Godthab'           => '(GMT-3:00) America/Godthab (Western Greenland Time)' ,
			'America/Jujuy'             => '(GMT-3:00) America/Jujuy (Argentine Time)' ,
			'America/Maceio'            => '(GMT-3:00) America/Maceio (Brasilia Time)' ,
			'America/Mendoza'           => '(GMT-3:00) America/Mendoza (Argentine Time)' ,
			'America/Miquelon'          => '(GMT-3:00) America/Miquelon (Pierre & Miquelon Standard Time)' ,
			'America/Montevideo'        => '(GMT-3:00) America/Montevideo (Uruguay Time)' ,
			'America/Paramaribo'        => '(GMT-3:00) America/Paramaribo (Suriname Time)' ,
			'America/Recife'            => '(GMT-3:00) America/Recife (Brasilia Time)' ,
			'America/Rosario'           => '(GMT-3:00) America/Rosario (Argentine Time)' ,
			'America/Santarem'          => '(GMT-3:00) America/Santarem (Brasilia Time)' ,
			'America/Sao_Paulo'         => '(GMT-3:00) America/Sao_Paulo (Brasilia Time)' ,
			'Antarctica/Rothera'        => '(GMT-3:00) Antarctica/Rothera (Rothera Time)' ,
			'Brazil/East'               => '(GMT-3:00) Brazil/East (Brasilia Time)' ,
			'America/Noronha'           => '(GMT-2:00) America/Noronha (Fernando de Noronha Time)' ,
			'Atlantic/South_Georgia'    => '(GMT-2:00) Atlantic/South_Georgia (South Georgia Standard Time)' ,
			'Brazil/DeNoronha'          => '(GMT-2:00) Brazil/DeNoronha (Fernando de Noronha Time)' ,
			'America/Scoresbysund'      => '(GMT-1:00) America/Scoresbysund (Eastern Greenland Time)' ,
			'Atlantic/Azores'           => '(GMT-1:00) Atlantic/Azores (Azores Time)' ,
			'Atlantic/Cape_Verde'       => '(GMT-1:00) Atlantic/Cape_Verde (Cape Verde Time)' ,
			'Africa/Abidjan'            => '(GMT+0:00) Africa/Abidjan (Greenwich Mean Time)' ,
			'Africa/Accra'              => '(GMT+0:00) Africa/Accra (Ghana Mean Time)' ,
			'Africa/Bamako'             => '(GMT+0:00) Africa/Bamako (Greenwich Mean Time)' ,
			'Africa/Banjul'             => '(GMT+0:00) Africa/Banjul (Greenwich Mean Time)' ,
			'Africa/Bissau'             => '(GMT+0:00) Africa/Bissau (Greenwich Mean Time)' ,
			'Africa/Casablanca'         => '(GMT+0:00) Africa/Casablanca (Western European Time)' ,
			'Africa/Conakry'            => '(GMT+0:00) Africa/Conakry (Greenwich Mean Time)' ,
			'Africa/Dakar'              => '(GMT+0:00) Africa/Dakar (Greenwich Mean Time)' ,
			'Africa/El_Aaiun'           => '(GMT+0:00) Africa/El_Aaiun (Western European Time)' ,
			'Africa/Freetown'           => '(GMT+0:00) Africa/Freetown (Greenwich Mean Time)' ,
			'Africa/Lome'               => '(GMT+0:00) Africa/Lome (Greenwich Mean Time)' ,
			'Africa/Monrovia'           => '(GMT+0:00) Africa/Monrovia (Greenwich Mean Time)' ,
			'Africa/Nouakchott'         => '(GMT+0:00) Africa/Nouakchott (Greenwich Mean Time)' ,
			'Africa/Ouagadougou'        => '(GMT+0:00) Africa/Ouagadougou (Greenwich Mean Time)' ,
			'Africa/Sao_Tome'           => '(GMT+0:00) Africa/Sao_Tome (Greenwich Mean Time)' ,
			'Africa/Timbuktu'           => '(GMT+0:00) Africa/Timbuktu (Greenwich Mean Time)' ,
			'America/Danmarkshavn'      => '(GMT+0:00) America/Danmarkshavn (Greenwich Mean Time)' ,
			'Atlantic/Canary'           => '(GMT+0:00) Atlantic/Canary (Western European Time)' ,
			'Atlantic/Faeroe'           => '(GMT+0:00) Atlantic/Faeroe (Western European Time)' ,
			'Atlantic/Faroe'            => '(GMT+0:00) Atlantic/Faroe (Western European Time)' ,
			'Atlantic/Madeira'          => '(GMT+0:00) Atlantic/Madeira (Western European Time)' ,
			'Atlantic/Reykjavik'        => '(GMT+0:00) Atlantic/Reykjavik (Greenwich Mean Time)' ,
			'Atlantic/St_Helena'        => '(GMT+0:00) Atlantic/St_Helena (Greenwich Mean Time)' ,
			'Europe/Belfast'            => '(GMT+0:00) Europe/Belfast (Greenwich Mean Time)' ,
			'Europe/Dublin'             => '(GMT+0:00) Europe/Dublin (Greenwich Mean Time)' ,
			'Europe/Guernsey'           => '(GMT+0:00) Europe/Guernsey (Greenwich Mean Time)' ,
			'Europe/Isle_of_Man'        => '(GMT+0:00) Europe/Isle_of_Man (Greenwich Mean Time)' ,
			'Europe/Jersey'             => '(GMT+0:00) Europe/Jersey (Greenwich Mean Time)' ,
			'Europe/Lisbon'             => '(GMT+0:00) Europe/Lisbon (Western European Time)' ,
			'Europe/London'             => '(GMT+0:00) Europe/London (Greenwich Mean Time)' ,
			'Africa/Algiers'            => '(GMT+1:00) Africa/Algiers (Central European Time)' ,
			'Africa/Bangui'             => '(GMT+1:00) Africa/Bangui (Western African Time)' ,
			'Africa/Brazzaville'        => '(GMT+1:00) Africa/Brazzaville (Western African Time)' ,
			'Africa/Ceuta'              => '(GMT+1:00) Africa/Ceuta (Central European Time)' ,
			'Africa/Douala'             => '(GMT+1:00) Africa/Douala (Western African Time)' ,
			'Africa/Kinshasa'           => '(GMT+1:00) Africa/Kinshasa (Western African Time)' ,
			'Africa/Lagos'              => '(GMT+1:00) Africa/Lagos (Western African Time)' ,
			'Africa/Libreville'         => '(GMT+1:00) Africa/Libreville (Western African Time)' ,
			'Africa/Luanda'             => '(GMT+1:00) Africa/Luanda (Western African Time)' ,
			'Africa/Malabo'             => '(GMT+1:00) Africa/Malabo (Western African Time)' ,
			'Africa/Ndjamena'           => '(GMT+1:00) Africa/Ndjamena (Western African Time)' ,
			'Africa/Niamey'             => '(GMT+1:00) Africa/Niamey (Western African Time)' ,
			'Africa/Porto-Novo'         => '(GMT+1:00) Africa/Porto-Novo (Western African Time)' ,
			'Africa/Tunis'              => '(GMT+1:00) Africa/Tunis (Central European Time)' ,
			'Africa/Windhoek'           => '(GMT+1:00) Africa/Windhoek (Western African Time)' ,
			'Arctic/Longyearbyen'       => '(GMT+1:00) Arctic/Longyearbyen (Central European Time)' ,
			'Atlantic/Jan_Mayen'        => '(GMT+1:00) Atlantic/Jan_Mayen (Central European Time)' ,
			'Europe/Amsterdam'          => '(GMT+1:00) Europe/Amsterdam (Central European Time)' ,
			'Europe/Andorra'            => '(GMT+1:00) Europe/Andorra (Central European Time)' ,
			'Europe/Belgrade'           => '(GMT+1:00) Europe/Belgrade (Central European Time)' ,
			'Europe/Berlin'             => '(GMT+1:00) Europe/Berlin (Central European Time)' ,
			'Europe/Bratislava'         => '(GMT+1:00) Europe/Bratislava (Central European Time)' ,
			'Europe/Brussels'           => '(GMT+1:00) Europe/Brussels (Central European Time)' ,
			'Europe/Budapest'           => '(GMT+1:00) Europe/Budapest (Central European Time)' ,
			'Europe/Copenhagen'         => '(GMT+1:00) Europe/Copenhagen (Central European Time)' ,
			'Europe/Gibraltar'          => '(GMT+1:00) Europe/Gibraltar (Central European Time)' ,
			'Europe/Ljubljana'          => '(GMT+1:00) Europe/Ljubljana (Central European Time)' ,
			'Europe/Luxembourg'         => '(GMT+1:00) Europe/Luxembourg (Central European Time)' ,
			'Europe/Madrid'             => '(GMT+1:00) Europe/Madrid (Central European Time)' ,
			'Europe/Malta'              => '(GMT+1:00) Europe/Malta (Central European Time)' ,
			'Europe/Monaco'             => '(GMT+1:00) Europe/Monaco (Central European Time)' ,
			'Europe/Oslo'               => '(GMT+1:00) Europe/Oslo (Central European Time)' ,
			'Europe/Paris'              => '(GMT+1:00) Europe/Paris (Central European Time)' ,
			'Europe/Podgorica'          => '(GMT+1:00) Europe/Podgorica (Central European Time)' ,
			'Europe/Prague'             => '(GMT+1:00) Europe/Prague (Central European Time)' ,
			'Europe/Rome'               => '(GMT+1:00) Europe/Rome (Central European Time)' ,
			'Europe/San_Marino'         => '(GMT+1:00) Europe/San_Marino (Central European Time)' ,
			'Europe/Sarajevo'           => '(GMT+1:00) Europe/Sarajevo (Central European Time)' ,
			'Europe/Skopje'             => '(GMT+1:00) Europe/Skopje (Central European Time)' ,
			'Europe/Stockholm'          => '(GMT+1:00) Europe/Stockholm (Central European Time)' ,
			'Europe/Tirane'             => '(GMT+1:00) Europe/Tirane (Central European Time)' ,
			'Europe/Vaduz'              => '(GMT+1:00) Europe/Vaduz (Central European Time)' ,
			'Europe/Vatican'            => '(GMT+1:00) Europe/Vatican (Central European Time)' ,
			'Europe/Vienna'             => '(GMT+1:00) Europe/Vienna (Central European Time)' ,
			'Europe/Warsaw'             => '(GMT+1:00) Europe/Warsaw (Central European Time)' ,
			'Europe/Zagreb'             => '(GMT+1:00) Europe/Zagreb (Central European Time)' ,
			'Europe/Zurich'             => '(GMT+1:00) Europe/Zurich (Central European Time)' ,
			'Africa/Blantyre'           => '(GMT+2:00) Africa/Blantyre (Central African Time)' ,
			'Africa/Bujumbura'          => '(GMT+2:00) Africa/Bujumbura (Central African Time)' ,
			'Africa/Cairo'              => '(GMT+2:00) Africa/Cairo (Eastern European Time)' ,
			'Africa/Gaborone'           => '(GMT+2:00) Africa/Gaborone (Central African Time)' ,
			'Africa/Harare'             => '(GMT+2:00) Africa/Harare (Central African Time)' ,
			'Africa/Johannesburg'       => '(GMT+2:00) Africa/Johannesburg (South Africa Standard Time)' ,
			'Africa/Kigali'             => '(GMT+2:00) Africa/Kigali (Central African Time)' ,
			'Africa/Lubumbashi'         => '(GMT+2:00) Africa/Lubumbashi (Central African Time)' ,
			'Africa/Lusaka'             => '(GMT+2:00) Africa/Lusaka (Central African Time)' ,
			'Africa/Maputo'             => '(GMT+2:00) Africa/Maputo (Central African Time)' ,
			'Africa/Maseru'             => '(GMT+2:00) Africa/Maseru (South Africa Standard Time)' ,
			'Africa/Mbabane'            => '(GMT+2:00) Africa/Mbabane (South Africa Standard Time)' ,
			'Africa/Tripoli'            => '(GMT+2:00) Africa/Tripoli (Eastern European Time)' ,
			'Asia/Amman'                => '(GMT+2:00) Asia/Amman (Eastern European Time)' ,
			'Asia/Beirut'               => '(GMT+2:00) Asia/Beirut (Eastern European Time)' ,
			'Asia/Damascus'             => '(GMT+2:00) Asia/Damascus (Eastern European Time)' ,
			'Asia/Gaza'                 => '(GMT+2:00) Asia/Gaza (Eastern European Time)' ,
			'Asia/Istanbul'             => '(GMT+2:00) Asia/Istanbul (Eastern European Time)' ,
			'Asia/Jerusalem'            => '(GMT+2:00) Asia/Jerusalem (Israel Standard Time)' ,
			'Asia/Nicosia'              => '(GMT+2:00) Asia/Nicosia (Eastern European Time)' ,
			'Asia/Tel_Aviv'             => '(GMT+2:00) Asia/Tel_Aviv (Israel Standard Time)' ,
			'Europe/Athens'             => '(GMT+2:00) Europe/Athens (Eastern European Time)' ,
			'Europe/Bucharest'          => '(GMT+2:00) Europe/Bucharest (Eastern European Time)' ,
			'Europe/Chisinau'           => '(GMT+2:00) Europe/Chisinau (Eastern European Time)' ,
			'Europe/Helsinki'           => '(GMT+2:00) Europe/Helsinki (Eastern European Time)' ,
			'Europe/Istanbul'           => '(GMT+2:00) Europe/Istanbul (Eastern European Time)' ,
			'Europe/Kaliningrad'        => '(GMT+2:00) Europe/Kaliningrad (Eastern European Time)' ,
			'Europe/Kiev'               => '(GMT+2:00) Europe/Kiev (Eastern European Time)' ,
			'Europe/Mariehamn'          => '(GMT+2:00) Europe/Mariehamn (Eastern European Time)' ,
			'Europe/Minsk'              => '(GMT+2:00) Europe/Minsk (Eastern European Time)' ,
			'Europe/Nicosia'            => '(GMT+2:00) Europe/Nicosia (Eastern European Time)' ,
			'Europe/Riga'               => '(GMT+2:00) Europe/Riga (Eastern European Time)' ,
			'Europe/Simferopol'         => '(GMT+2:00) Europe/Simferopol (Eastern European Time)' ,
			'Europe/Sofia'              => '(GMT+2:00) Europe/Sofia (Eastern European Time)' ,
			'Europe/Tallinn'            => '(GMT+2:00) Europe/Tallinn (Eastern European Time)' ,
			'Europe/Tiraspol'           => '(GMT+2:00) Europe/Tiraspol (Eastern European Time)' ,
			'Europe/Uzhgorod'           => '(GMT+2:00) Europe/Uzhgorod (Eastern European Time)' ,
			'Europe/Vilnius'            => '(GMT+2:00) Europe/Vilnius (Eastern European Time)' ,
			'Europe/Zaporozhye'         => '(GMT+2:00) Europe/Zaporozhye (Eastern European Time)' ,
			'Africa/Addis_Ababa'        => '(GMT+3:00) Africa/Addis_Ababa (Eastern African Time)' ,
			'Africa/Asmara'             => '(GMT+3:00) Africa/Asmara (Eastern African Time)' ,
			'Africa/Asmera'             => '(GMT+3:00) Africa/Asmera (Eastern African Time)' ,
			'Africa/Dar_es_Salaam'      => '(GMT+3:00) Africa/Dar_es_Salaam (Eastern African Time)' ,
			'Africa/Djibouti'           => '(GMT+3:00) Africa/Djibouti (Eastern African Time)' ,
			'Africa/Kampala'            => '(GMT+3:00) Africa/Kampala (Eastern African Time)' ,
			'Africa/Khartoum'           => '(GMT+3:00) Africa/Khartoum (Eastern African Time)' ,
			'Africa/Mogadishu'          => '(GMT+3:00) Africa/Mogadishu (Eastern African Time)' ,
			'Africa/Nairobi'            => '(GMT+3:00) Africa/Nairobi (Eastern African Time)' ,
			'Antarctica/Syowa'          => '(GMT+3:00) Antarctica/Syowa (Syowa Time)' ,
			'Asia/Aden'                 => '(GMT+3:00) Asia/Aden (Arabia Standard Time)' ,
			'Asia/Baghdad'              => '(GMT+3:00) Asia/Baghdad (Arabia Standard Time)' ,
			'Asia/Bahrain'              => '(GMT+3:00) Asia/Bahrain (Arabia Standard Time)' ,
			'Asia/Kuwait'               => '(GMT+3:00) Asia/Kuwait (Arabia Standard Time)' ,
			'Asia/Qatar'                => '(GMT+3:00) Asia/Qatar (Arabia Standard Time)' ,
			'Europe/Moscow'             => '(GMT+3:00) Europe/Moscow (Moscow Standard Time)' ,
			'Europe/Volgograd'          => '(GMT+3:00) Europe/Volgograd (Volgograd Time)' ,
			'Indian/Antananarivo'       => '(GMT+3:00) Indian/Antananarivo (Eastern African Time)' ,
			'Indian/Comoro'             => '(GMT+3:00) Indian/Comoro (Eastern African Time)' ,
			'Indian/Mayotte'            => '(GMT+3:00) Indian/Mayotte (Eastern African Time)' ,
			'Asia/Tehran'               => '(GMT+3:30) Asia/Tehran (Iran Standard Time)' ,
			'Asia/Baku'                 => '(GMT+4:00) Asia/Baku (Azerbaijan Time)' ,
			'Asia/Dubai'                => '(GMT+4:00) Asia/Dubai (Gulf Standard Time)' ,
			'Asia/Muscat'               => '(GMT+4:00) Asia/Muscat (Gulf Standard Time)' ,
			'Asia/Tbilisi'              => '(GMT+4:00) Asia/Tbilisi (Georgia Time)' ,
			'Asia/Yerevan'              => '(GMT+4:00) Asia/Yerevan (Armenia Time)' ,
			'Europe/Samara'             => '(GMT+4:00) Europe/Samara (Samara Time)' ,
			'Indian/Mahe'               => '(GMT+4:00) Indian/Mahe (Seychelles Time)' ,
			'Indian/Mauritius'          => '(GMT+4:00) Indian/Mauritius (Mauritius Time)' ,
			'Indian/Reunion'            => '(GMT+4:00) Indian/Reunion (Reunion Time)' ,
			'Asia/Kabul'                => '(GMT+4:30) Asia/Kabul (Afghanistan Time)' ,
			'Asia/Aqtau'                => '(GMT+5:00) Asia/Aqtau (Aqtau Time)' ,
			'Asia/Aqtobe'               => '(GMT+5:00) Asia/Aqtobe (Aqtobe Time)' ,
			'Asia/Ashgabat'             => '(GMT+5:00) Asia/Ashgabat (Turkmenistan Time)' ,
			'Asia/Ashkhabad'            => '(GMT+5:00) Asia/Ashkhabad (Turkmenistan Time)' ,
			'Asia/Dushanbe'             => '(GMT+5:00) Asia/Dushanbe (Tajikistan Time)' ,
			'Asia/Karachi'              => '(GMT+5:00) Asia/Karachi (Pakistan Time)' ,
			'Asia/Oral'                 => '(GMT+5:00) Asia/Oral (Oral Time)' ,
			'Asia/Samarkand'            => '(GMT+5:00) Asia/Samarkand (Uzbekistan Time)' ,
			'Asia/Tashkent'             => '(GMT+5:00) Asia/Tashkent (Uzbekistan Time)' ,
			'Asia/Yekaterinburg'        => '(GMT+5:00) Asia/Yekaterinburg (Yekaterinburg Time)' ,
			'Indian/Kerguelen'          => '(GMT+5:00) Indian/Kerguelen (French Southern & Antarctic Lands Time)' ,
			'Indian/Maldives'           => '(GMT+5:00) Indian/Maldives (Maldives Time)' ,
			'Asia/Calcutta'             => '(GMT+5:30) Asia/Calcutta (India Standard Time)' ,
			'Asia/Colombo'              => '(GMT+5:30) Asia/Colombo (India Standard Time)' ,
			'Asia/Kolkata'              => '(GMT+5:30) Asia/Kolkata (India Standard Time)' ,
			'Asia/Katmandu'             => '(GMT+5:45) Asia/Katmandu (Nepal Time)' ,
			'Antarctica/Mawson'         => '(GMT+6:00) Antarctica/Mawson (Mawson Time)' ,
			'Antarctica/Vostok'         => '(GMT+6:00) Antarctica/Vostok (Vostok Time)' ,
			'Asia/Almaty'               => '(GMT+6:00) Asia/Almaty (Alma-Ata Time)' ,
			'Asia/Bishkek'              => '(GMT+6:00) Asia/Bishkek (Kirgizstan Time)' ,
			'Asia/Dacca'                => '(GMT+6:00) Asia/Dacca (Bangladesh Time)' ,
			'Asia/Dhaka'                => '(GMT+6:00) Asia/Dhaka (Bangladesh Time)' ,
			'Asia/Novosibirsk'          => '(GMT+6:00) Asia/Novosibirsk (Novosibirsk Time)' ,
			'Asia/Omsk'                 => '(GMT+6:00) Asia/Omsk (Omsk Time)' ,
			'Asia/Qyzylorda'            => '(GMT+6:00) Asia/Qyzylorda (Qyzylorda Time)' ,
			'Asia/Thimbu'               => '(GMT+6:00) Asia/Thimbu (Bhutan Time)' ,
			'Asia/Thimphu'              => '(GMT+6:00) Asia/Thimphu (Bhutan Time)' ,
			'Indian/Chagos'             => '(GMT+6:00) Indian/Chagos (Indian Ocean Territory Time)' ,
			'Asia/Rangoon'              => '(GMT+6:30) Asia/Rangoon (Myanmar Time)' ,
			'Indian/Cocos'              => '(GMT+6:30) Indian/Cocos (Cocos Islands Time)' ,
			'Antarctica/Davis'          => '(GMT+7:00) Antarctica/Davis (Davis Time)' ,
			'Asia/Bangkok'              => '(GMT+7:00) Asia/Bangkok (Indochina Time)' ,
			'Asia/Ho_Chi_Minh'          => '(GMT+7:00) Asia/Ho_Chi_Minh (Indochina Time)' ,
			'Asia/Hovd'                 => '(GMT+7:00) Asia/Hovd (Hovd Time)' ,
			'Asia/Jakarta'              => '(GMT+7:00) Asia/Jakarta (West Indonesia Time)' ,
			'Asia/Krasnoyarsk'          => '(GMT+7:00) Asia/Krasnoyarsk (Krasnoyarsk Time)' ,
			'Asia/Phnom_Penh'           => '(GMT+7:00) Asia/Phnom_Penh (Indochina Time)' ,
			'Asia/Pontianak'            => '(GMT+7:00) Asia/Pontianak (West Indonesia Time)' ,
			'Asia/Saigon'               => '(GMT+7:00) Asia/Saigon (Indochina Time)' ,
			'Asia/Vientiane'            => '(GMT+7:00) Asia/Vientiane (Indochina Time)' ,
			'Indian/Christmas'          => '(GMT+7:00) Indian/Christmas (Christmas Island Time)' ,
			'Antarctica/Casey'          => '(GMT+8:00) Antarctica/Casey (Western Standard Time (Australia))' ,
			'Asia/Brunei'               => '(GMT+8:00) Asia/Brunei (Brunei Time)' ,
			'Asia/Choibalsan'           => '(GMT+8:00) Asia/Choibalsan (Choibalsan Time)' ,
			'Asia/Chongqing'            => '(GMT+8:00) Asia/Chongqing (China Standard Time)' ,
			'Asia/Chungking'            => '(GMT+8:00) Asia/Chungking (China Standard Time)' ,
			'Asia/Harbin'               => '(GMT+8:00) Asia/Harbin (China Standard Time)' ,
			'Asia/Hong_Kong'            => '(GMT+8:00) Asia/Hong_Kong (Hong Kong Time)' ,
			'Asia/Irkutsk'              => '(GMT+8:00) Asia/Irkutsk (Irkutsk Time)' ,
			'Asia/Kashgar'              => '(GMT+8:00) Asia/Kashgar (China Standard Time)' ,
			'Asia/Kuala_Lumpur'         => '(GMT+8:00) Asia/Kuala_Lumpur (Malaysia Time)' ,
			'Asia/Kuching'              => '(GMT+8:00) Asia/Kuching (Malaysia Time)' ,
			'Asia/Macao'                => '(GMT+8:00) Asia/Macao (China Standard Time)' ,
			'Asia/Macau'                => '(GMT+8:00) Asia/Macau (China Standard Time)' ,
			'Asia/Makassar'             => '(GMT+8:00) Asia/Makassar (Central Indonesia Time)' ,
			'Asia/Manila'               => '(GMT+8:00) Asia/Manila (Philippines Time)' ,
			'Asia/Shanghai'             => '(GMT+8:00) Asia/Shanghai (China Standard Time)' ,
			'Asia/Singapore'            => '(GMT+8:00) Asia/Singapore (Singapore Time)' ,
			'Asia/Taipei'               => '(GMT+8:00) Asia/Taipei (China Standard Time)' ,
			'Asia/Ujung_Pandang'        => '(GMT+8:00) Asia/Ujung_Pandang (Central Indonesia Time)' ,
			'Asia/Ulaanbaatar'          => '(GMT+8:00) Asia/Ulaanbaatar (Ulaanbaatar Time)' ,
			'Asia/Ulan_Bator'           => '(GMT+8:00) Asia/Ulan_Bator (Ulaanbaatar Time)' ,
			'Asia/Urumqi'               => '(GMT+8:00) Asia/Urumqi (China Standard Time)' ,
			'Australia/Perth'           => '(GMT+8:00) Australia/Perth (Western Standard Time (Australia))' ,
			'Australia/West'            => '(GMT+8:00) Australia/West (Western Standard Time (Australia))' ,
			'Australia/Eucla'           => '(GMT+8:45) Australia/Eucla (Central Western Standard Time (Australia))' ,
			'Asia/Dili'                 => '(GMT+9:00) Asia/Dili (Timor-Leste Time)' ,
			'Asia/Jayapura'             => '(GMT+9:00) Asia/Jayapura (East Indonesia Time)' ,
			'Asia/Pyongyang'            => '(GMT+9:00) Asia/Pyongyang (Korea Standard Time)' ,
			'Asia/Seoul'                => '(GMT+9:00) Asia/Seoul (Korea Standard Time)' ,
			'Asia/Tokyo'                => '(GMT+9:00) Asia/Tokyo (Japan Standard Time)' ,
			'Asia/Yakutsk'              => '(GMT+9:00) Asia/Yakutsk (Yakutsk Time)' ,
			'Australia/Adelaide'        => '(GMT+9:30) Australia/Adelaide (Central Standard Time (South Australia))' ,
			'Australia/Broken_Hill'     => '(GMT+9:30) Australia/Broken_Hill (Central Standard Time (South Australia/New South Wales))' ,
			'Australia/Darwin'          => '(GMT+9:30) Australia/Darwin (Central Standard Time (Northern Territory))' ,
			'Australia/North'           => '(GMT+9:30) Australia/North (Central Standard Time (Northern Territory))' ,
			'Australia/South'           => '(GMT+9:30) Australia/South (Central Standard Time (South Australia))' ,
			'Australia/Yancowinna'      => '(GMT+9:30) Australia/Yancowinna (Central Standard Time (South Australia/New South Wales))' ,
			'Antarctica/DumontDUrville' => '(GMT+10:00) Antarctica/DumontDUrville (Dumont-d\'Urville Time)' ,
			'Asia/Sakhalin'             => '(GMT+10:00) Asia/Sakhalin (Sakhalin Time)' ,
			'Asia/Vladivostok'          => '(GMT+10:00) Asia/Vladivostok (Vladivostok Time)' ,
			'Australia/ACT'             => '(GMT+10:00) Australia/ACT (Eastern Standard Time (New South Wales))' ,
			'Australia/Brisbane'        => '(GMT+10:00) Australia/Brisbane (Eastern Standard Time (Queensland))' ,
			'Australia/Canberra'        => '(GMT+10:00) Australia/Canberra (Eastern Standard Time (New South Wales))' ,
			'Australia/Currie'          => '(GMT+10:00) Australia/Currie (Eastern Standard Time (New South Wales))' ,
			'Australia/Hobart'          => '(GMT+10:00) Australia/Hobart (Eastern Standard Time (Tasmania))' ,
			'Australia/Lindeman'        => '(GMT+10:00) Australia/Lindeman (Eastern Standard Time (Queensland))' ,
			'Australia/Melbourne'       => '(GMT+10:00) Australia/Melbourne (Eastern Standard Time (Victoria))' ,
			'Australia/NSW'             => '(GMT+10:00) Australia/NSW (Eastern Standard Time (New South Wales))' ,
			'Australia/Queensland'      => '(GMT+10:00) Australia/Queensland (Eastern Standard Time (Queensland))' ,
			'Australia/Sydney'          => '(GMT+10:00) Australia/Sydney (Eastern Standard Time (New South Wales))' ,
			'Australia/Tasmania'        => '(GMT+10:00) Australia/Tasmania (Eastern Standard Time (Tasmania))' ,
			'Australia/Victoria'        => '(GMT+10:00) Australia/Victoria (Eastern Standard Time (Victoria))' ,
			'Australia/LHI'             => '(GMT+10:30) Australia/LHI (Lord Howe Standard Time)' ,
			'Australia/Lord_Howe'       => '(GMT+10:30) Australia/Lord_Howe (Lord Howe Standard Time)' ,
			'Asia/Magadan'              => '(GMT+11:00) Asia/Magadan (Magadan Time)' ,
			'Antarctica/McMurdo'        => '(GMT+12:00) Antarctica/McMurdo (New Zealand Standard Time)' ,
			'Antarctica/South_Pole'     => '(GMT+12:00) Antarctica/South_Pole (New Zealand Standard Time)' ,
			'Asia/Anadyr'               => '(GMT+12:00) Asia/Anadyr (Anadyr Time)' ,
			'Asia/Kamchatka'            => '(GMT+12:00) Asia/Kamchatka (Petropavlovsk-Kamchatski Time)'
		);
		
		
		$html = '<select name="' . $formName . '" id="' . $formName . '">';
		
		foreach ( $timezones as $zone => $name )
		{
			
			$isSelected = ( ! empty( $valueHolder ) && $valueHolder === $zone ) ? "selected" : "" ;
			$html .= '<option value="' . $zone . '" '.$isSelected.' >' . $name . '</option>';
		}
		$html .= '</select>';
		
		return $html;
		
	}
	
	function faArray()
	{
		
		return array(
			"fa-500px" ,
			"fa-address-book" ,
			"fa-address-book-o" ,
			"fa-address-card" ,
			"fa-address-card-o" ,
			"fa-adjust" ,
			"fa-adn" ,
			"fa-align-center" ,
			"fa-align-justify" ,
			"fa-align-left" ,
			"fa-align-right" ,
			"fa-amazon" ,
			"fa-ambulance" ,
			"fa-american-sign-language-interpreting" ,
			"fa-anchor" ,
			"fa-android" ,
			"fa-angellist" ,
			"fa-angle-double-down" ,
			"fa-angle-double-left" ,
			"fa-angle-double-right" ,
			"fa-angle-double-up" ,
			"fa-angle-down" ,
			"fa-angle-left" ,
			"fa-angle-right" ,
			"fa-angle-up" ,
			"fa-apple" ,
			"fa-archive" ,
			"fa-area-chart" ,
			"fa-arrow-circle-down" ,
			"fa-arrow-circle-left" ,
			"fa-arrow-circle-o-down" ,
			"fa-arrow-circle-o-left" ,
			"fa-arrow-circle-o-right" ,
			"fa-arrow-circle-o-up" ,
			"fa-arrow-circle-right" ,
			"fa-arrow-circle-up" ,
			"fa-arrow-down" ,
			"fa-arrow-left" ,
			"fa-arrow-right" ,
			"fa-arrow-up" ,
			"fa-arrows" ,
			"fa-arrows-alt" ,
			"fa-arrows-h" ,
			"fa-arrows-v" ,
			"fa-assistive-listening-systems" ,
			"fa-asterisk" ,
			"fa-at" ,
			"fa-audio-description" ,
			"fa-backward" ,
			"fa-balance-scale" ,
			"fa-ban" ,
			"fa-bandcamp" ,
			"fa-bar-chart" ,
			"fa-barcode" ,
			"fa-bars" ,
			"fa-bath" ,
			"fa-battery-empty" ,
			"fa-battery-full" ,
			"fa-battery-half" ,
			"fa-battery-quarter" ,
			"fa-battery-three-quarters" ,
			"fa-bed" ,
			"fa-beer" ,
			"fa-behance" ,
			"fa-behance-square" ,
			"fa-bell" ,
			"fa-bell-o" ,
			"fa-bell-slash" ,
			"fa-bell-slash-o" ,
			"fa-bicycle" ,
			"fa-binoculars" ,
			"fa-birthday-cake" ,
			"fa-bitbucket" ,
			"fa-bitbucket-square" ,
			"fa-black-tie" ,
			"fa-blind" ,
			"fa-bluetooth" ,
			"fa-bluetooth-b" ,
			"fa-bold" ,
			"fa-bolt" ,
			"fa-bomb" ,
			"fa-book" ,
			"fa-bookmark" ,
			"fa-bookmark-o" ,
			"fa-braille" ,
			"fa-briefcase" ,
			"fa-btc" ,
			"fa-bug" ,
			"fa-building" ,
			"fa-building-o" ,
			"fa-bullhorn" ,
			"fa-bullseye" ,
			"fa-bus" ,
			"fa-buysellads" ,
			"fa-calculator" ,
			"fa-calendar" ,
			"fa-calendar-check-o" ,
			"fa-calendar-minus-o" ,
			"fa-calendar-o" ,
			"fa-calendar-plus-o" ,
			"fa-calendar-times-o" ,
			"fa-camera" ,
			"fa-camera-retro" ,
			"fa-car" ,
			"fa-caret-down" ,
			"fa-caret-left" ,
			"fa-caret-right" ,
			"fa-caret-square-o-down" ,
			"fa-caret-square-o-left" ,
			"fa-caret-square-o-right" ,
			"fa-caret-square-o-up" ,
			"fa-caret-up" ,
			"fa-cart-arrow-down" ,
			"fa-cart-plus" ,
			"fa-cc" ,
			"fa-cc-amex" ,
			"fa-cc-diners-club" ,
			"fa-cc-discover" ,
			"fa-cc-jcb" ,
			"fa-cc-mastercard" ,
			"fa-cc-paypal" ,
			"fa-cc-stripe" ,
			"fa-cc-visa" ,
			"fa-certificate" ,
			"fa-chain-broken" ,
			"fa-check" ,
			"fa-check-circle" ,
			"fa-check-circle-o" ,
			"fa-check-square" ,
			"fa-check-square-o" ,
			"fa-chevron-circle-down" ,
			"fa-chevron-circle-left" ,
			"fa-chevron-circle-right" ,
			"fa-chevron-circle-up" ,
			"fa-chevron-down" ,
			"fa-chevron-left" ,
			"fa-chevron-right" ,
			"fa-chevron-up" ,
			"fa-child" ,
			"fa-chrome" ,
			"fa-circle" ,
			"fa-circle-o" ,
			"fa-circle-o-notch" ,
			"fa-circle-thin" ,
			"fa-clipboard" ,
			"fa-clock-o" ,
			"fa-clone" ,
			"fa-cloud" ,
			"fa-cloud-download" ,
			"fa-cloud-upload" ,
			"fa-code" ,
			"fa-code-fork" ,
			"fa-codepen" ,
			"fa-codiepie" ,
			"fa-coffee" ,
			"fa-cog" ,
			"fa-cogs" ,
			"fa-columns" ,
			"fa-comment" ,
			"fa-comment-o" ,
			"fa-commenting" ,
			"fa-commenting-o" ,
			"fa-comments" ,
			"fa-comments-o" ,
			"fa-compass" ,
			"fa-compress" ,
			"fa-connectdevelop" ,
			"fa-contao" ,
			"fa-copyright" ,
			"fa-creative-commons" ,
			"fa-credit-card" ,
			"fa-credit-card-alt" ,
			"fa-crop" ,
			"fa-crosshairs" ,
			"fa-css3" ,
			"fa-cube" ,
			"fa-cubes" ,
			"fa-cutlery" ,
			"fa-dashcube" ,
			"fa-database" ,
			"fa-deaf" ,
			"fa-delicious" ,
			"fa-desktop" ,
			"fa-deviantart" ,
			"fa-diamond" ,
			"fa-digg" ,
			"fa-dot-circle-o" ,
			"fa-download" ,
			"fa-dribbble" ,
			"fa-dropbox" ,
			"fa-drupal" ,
			"fa-edge" ,
			"fa-eercast" ,
			"fa-eject" ,
			"fa-ellipsis-h" ,
			"fa-ellipsis-v" ,
			"fa-empire" ,
			"fa-envelope" ,
			"fa-envelope-o" ,
			"fa-envelope-open" ,
			"fa-envelope-open-o" ,
			"fa-envelope-square" ,
			"fa-envira" ,
			"fa-eraser" ,
			"fa-etsy" ,
			"fa-eur" ,
			"fa-exchange" ,
			"fa-exclamation" ,
			"fa-exclamation-circle" ,
			"fa-exclamation-triangle" ,
			"fa-expand" ,
			"fa-expeditedssl" ,
			"fa-external-link" ,
			"fa-external-link-square" ,
			"fa-eye" ,
			"fa-eye-slash" ,
			"fa-eyedropper" ,
			"fa-facebook" ,
			"fa-facebook-official" ,
			"fa-facebook-square" ,
			"fa-fast-backward" ,
			"fa-fast-forward" ,
			"fa-fax" ,
			"fa-female" ,
			"fa-fighter-jet" ,
			"fa-file" ,
			"fa-file-archive-o" ,
			"fa-file-audio-o" ,
			"fa-file-code-o" ,
			"fa-file-excel-o" ,
			"fa-file-image-o" ,
			"fa-file-o" ,
			"fa-file-pdf-o" ,
			"fa-file-powerpoint-o" ,
			"fa-file-text" ,
			"fa-file-text-o" ,
			"fa-file-video-o" ,
			"fa-file-word-o" ,
			"fa-files-o" ,
			"fa-film" ,
			"fa-filter" ,
			"fa-fire" ,
			"fa-fire-extinguisher" ,
			"fa-firefox" ,
			"fa-first-order" ,
			"fa-flag" ,
			"fa-flag-checkered" ,
			"fa-flag-o" ,
			"fa-flask" ,
			"fa-flickr" ,
			"fa-floppy-o" ,
			"fa-folder" ,
			"fa-folder-o" ,
			"fa-folder-open" ,
			"fa-folder-open-o" ,
			"fa-font" ,
			"fa-font-awesome" ,
			"fa-fonticons" ,
			"fa-fort-awesome" ,
			"fa-forumbee" ,
			"fa-forward" ,
			"fa-foursquare" ,
			"fa-free-code-camp" ,
			"fa-frown-o" ,
			"fa-futbol-o" ,
			"fa-gamepad" ,
			"fa-gavel" ,
			"fa-gbp" ,
			"fa-genderless" ,
			"fa-get-pocket" ,
			"fa-gg" ,
			"fa-gg-circle" ,
			"fa-gift" ,
			"fa-git" ,
			"fa-git-square" ,
			"fa-github" ,
			"fa-github-alt" ,
			"fa-github-square" ,
			"fa-gitlab" ,
			"fa-glass" ,
			"fa-glide" ,
			"fa-glide-g" ,
			"fa-globe" ,
			"fa-google" ,
			"fa-google-plus" ,
			"fa-google-plus-official" ,
			"fa-google-plus-square" ,
			"fa-google-wallet" ,
			"fa-graduation-cap" ,
			"fa-gratipay" ,
			"fa-grav" ,
			"fa-h-square" ,
			"fa-hacker-news" ,
			"fa-hand-lizard-o" ,
			"fa-hand-o-down" ,
			"fa-hand-o-left" ,
			"fa-hand-o-right" ,
			"fa-hand-o-up" ,
			"fa-hand-paper-o" ,
			"fa-hand-peace-o" ,
			"fa-hand-pointer-o" ,
			"fa-hand-rock-o" ,
			"fa-hand-scissors-o" ,
			"fa-hand-spock-o" ,
			"fa-handshake-o" ,
			"fa-hashtag" ,
			"fa-hdd-o" ,
			"fa-header" ,
			"fa-headphones" ,
			"fa-heart" ,
			"fa-heart-o" ,
			"fa-heartbeat" ,
			"fa-history" ,
			"fa-home" ,
			"fa-hospital-o" ,
			"fa-hourglass" ,
			"fa-hourglass-end" ,
			"fa-hourglass-half" ,
			"fa-hourglass-o" ,
			"fa-hourglass-start" ,
			"fa-houzz" ,
			"fa-html5" ,
			"fa-i-cursor" ,
			"fa-id-badge" ,
			"fa-id-card" ,
			"fa-id-card-o" ,
			"fa-ils" ,
			"fa-imdb" ,
			"fa-inbox" ,
			"fa-indent" ,
			"fa-industry" ,
			"fa-info" ,
			"fa-info-circle" ,
			"fa-inr" ,
			"fa-instagram" ,
			"fa-internet-explorer" ,
			"fa-ioxhost" ,
			"fa-italic" ,
			"fa-joomla" ,
			"fa-jpy" ,
			"fa-jsfiddle" ,
			"fa-key" ,
			"fa-keyboard-o" ,
			"fa-krw" ,
			"fa-language" ,
			"fa-laptop" ,
			"fa-lastfm" ,
			"fa-lastfm-square" ,
			"fa-leaf" ,
			"fa-leanpub" ,
			"fa-lemon-o" ,
			"fa-level-down" ,
			"fa-level-up" ,
			"fa-life-ring" ,
			"fa-lightbulb-o" ,
			"fa-line-chart" ,
			"fa-link" ,
			"fa-linkedin" ,
			"fa-linkedin-square" ,
			"fa-linode" ,
			"fa-linux" ,
			"fa-list" ,
			"fa-list-alt" ,
			"fa-list-ol" ,
			"fa-list-ul" ,
			"fa-location-arrow" ,
			"fa-lock" ,
			"fa-long-arrow-down" ,
			"fa-long-arrow-left" ,
			"fa-long-arrow-right" ,
			"fa-long-arrow-up" ,
			"fa-low-vision" ,
			"fa-magic" ,
			"fa-magnet" ,
			"fa-male" ,
			"fa-map" ,
			"fa-map-marker" ,
			"fa-map-o" ,
			"fa-map-pin" ,
			"fa-map-signs" ,
			"fa-mars" ,
			"fa-mars-double" ,
			"fa-mars-stroke" ,
			"fa-mars-stroke-h" ,
			"fa-mars-stroke-v" ,
			"fa-maxcdn" ,
			"fa-meanpath" ,
			"fa-medium" ,
			"fa-medkit" ,
			"fa-meetup" ,
			"fa-meh-o" ,
			"fa-mercury" ,
			"fa-microchip" ,
			"fa-microphone" ,
			"fa-microphone-slash" ,
			"fa-minus" ,
			"fa-minus-circle" ,
			"fa-minus-square" ,
			"fa-minus-square-o" ,
			"fa-mixcloud" ,
			"fa-mobile" ,
			"fa-modx" ,
			"fa-money" ,
			"fa-moon-o" ,
			"fa-motorcycle" ,
			"fa-mouse-pointer" ,
			"fa-music" ,
			"fa-neuter" ,
			"fa-newspaper-o" ,
			"fa-object-group" ,
			"fa-object-ungroup" ,
			"fa-odnoklassniki" ,
			"fa-odnoklassniki-square" ,
			"fa-opencart" ,
			"fa-openid" ,
			"fa-opera" ,
			"fa-optin-monster" ,
			"fa-outdent" ,
			"fa-pagelines" ,
			"fa-paint-brush" ,
			"fa-paper-plane" ,
			"fa-paper-plane-o" ,
			"fa-paperclip" ,
			"fa-paragraph" ,
			"fa-pause" ,
			"fa-pause-circle" ,
			"fa-pause-circle-o" ,
			"fa-paw" ,
			"fa-paypal" ,
			"fa-pencil" ,
			"fa-pencil-square" ,
			"fa-pencil-square-o" ,
			"fa-percent" ,
			"fa-phone" ,
			"fa-phone-square" ,
			"fa-picture-o" ,
			"fa-pie-chart" ,
			"fa-pied-piper" ,
			"fa-pied-piper-alt" ,
			"fa-pied-piper-pp" ,
			"fa-pinterest" ,
			"fa-pinterest-p" ,
			"fa-pinterest-square" ,
			"fa-plane" ,
			"fa-play" ,
			"fa-play-circle" ,
			"fa-play-circle-o" ,
			"fa-plug" ,
			"fa-plus" ,
			"fa-plus-circle" ,
			"fa-plus-square" ,
			"fa-plus-square-o" ,
			"fa-podcast" ,
			"fa-power-off" ,
			"fa-print" ,
			"fa-product-hunt" ,
			"fa-puzzle-piece" ,
			"fa-qq" ,
			"fa-qrcode" ,
			"fa-question" ,
			"fa-question-circle" ,
			"fa-question-circle-o" ,
			"fa-quora" ,
			"fa-quote-left" ,
			"fa-quote-right" ,
			"fa-random" ,
			"fa-ravelry" ,
			"fa-rebel" ,
			"fa-recycle" ,
			"fa-reddit" ,
			"fa-reddit-alien" ,
			"fa-reddit-square" ,
			"fa-refresh" ,
			"fa-registered" ,
			"fa-renren" ,
			"fa-repeat" ,
			"fa-reply" ,
			"fa-reply-all" ,
			"fa-retweet" ,
			"fa-road" ,
			"fa-rocket" ,
			"fa-rss" ,
			"fa-rss-square" ,
			"fa-rub" ,
			"fa-safari" ,
			"fa-scissors" ,
			"fa-scribd" ,
			"fa-search" ,
			"fa-search-minus" ,
			"fa-search-plus" ,
			"fa-sellsy" ,
			"fa-server" ,
			"fa-share" ,
			"fa-share-alt" ,
			"fa-share-alt-square" ,
			"fa-share-square" ,
			"fa-share-square-o" ,
			"fa-shield" ,
			"fa-ship" ,
			"fa-shirtsinbulk" ,
			"fa-shopping-bag" ,
			"fa-shopping-basket" ,
			"fa-shopping-cart" ,
			"fa-shower" ,
			"fa-sign-in" ,
			"fa-sign-language" ,
			"fa-sign-out" ,
			"fa-signal" ,
			"fa-simplybuilt" ,
			"fa-sitemap" ,
			"fa-skyatlas" ,
			"fa-skype" ,
			"fa-slack" ,
			"fa-sliders" ,
			"fa-slideshare" ,
			"fa-smile-o" ,
			"fa-snapchat" ,
			"fa-snapchat-ghost" ,
			"fa-snapchat-square" ,
			"fa-snowflake-o" ,
			"fa-sort" ,
			"fa-sort-alpha-asc" ,
			"fa-sort-alpha-desc" ,
			"fa-sort-amount-asc" ,
			"fa-sort-amount-desc" ,
			"fa-sort-asc" ,
			"fa-sort-desc" ,
			"fa-sort-numeric-asc" ,
			"fa-sort-numeric-desc" ,
			"fa-soundcloud" ,
			"fa-space-shuttle" ,
			"fa-spinner" ,
			"fa-spoon" ,
			"fa-spotify" ,
			"fa-square" ,
			"fa-square-o" ,
			"fa-stack-exchange" ,
			"fa-stack-overflow" ,
			"fa-star" ,
			"fa-star-half" ,
			"fa-star-half-o" ,
			"fa-star-o" ,
			"fa-steam" ,
			"fa-steam-square" ,
			"fa-step-backward" ,
			"fa-step-forward" ,
			"fa-stethoscope" ,
			"fa-sticky-note" ,
			"fa-sticky-note-o" ,
			"fa-stop" ,
			"fa-stop-circle" ,
			"fa-stop-circle-o" ,
			"fa-street-view" ,
			"fa-strikethrough" ,
			"fa-stumbleupon" ,
			"fa-stumbleupon-circle" ,
			"fa-subscript" ,
			"fa-subway" ,
			"fa-suitcase" ,
			"fa-sun-o" ,
			"fa-superpowers" ,
			"fa-superscript" ,
			"fa-table" ,
			"fa-tablet" ,
			"fa-tachometer" ,
			"fa-tag" ,
			"fa-tags" ,
			"fa-tasks" ,
			"fa-taxi" ,
			"fa-telegram" ,
			"fa-television" ,
			"fa-tencent-weibo" ,
			"fa-terminal" ,
			"fa-text-height" ,
			"fa-text-width" ,
			"fa-th" ,
			"fa-th-large" ,
			"fa-th-list" ,
			"fa-themeisle" ,
			"fa-thermometer-empty" ,
			"fa-thermometer-full" ,
			"fa-thermometer-half" ,
			"fa-thermometer-quarter" ,
			"fa-thermometer-three-quarters" ,
			"fa-thumb-tack" ,
			"fa-thumbs-down" ,
			"fa-thumbs-o-down" ,
			"fa-thumbs-o-up" ,
			"fa-thumbs-up" ,
			"fa-ticket" ,
			"fa-times" ,
			"fa-times-circle" ,
			"fa-times-circle-o" ,
			"fa-tint" ,
			"fa-toggle-off" ,
			"fa-toggle-on" ,
			"fa-trademark" ,
			"fa-train" ,
			"fa-transgender" ,
			"fa-transgender-alt" ,
			"fa-trash" ,
			"fa-trash-o" ,
			"fa-tree" ,
			"fa-trello" ,
			"fa-tripadvisor" ,
			"fa-trophy" ,
			"fa-truck" ,
			"fa-try" ,
			"fa-tty" ,
			"fa-tumblr" ,
			"fa-tumblr-square" ,
			"fa-twitch" ,
			"fa-twitter" ,
			"fa-twitter-square" ,
			"fa-umbrella" ,
			"fa-underline" ,
			"fa-undo" ,
			"fa-universal-access" ,
			"fa-university" ,
			"fa-unlock" ,
			"fa-unlock-alt" ,
			"fa-upload" ,
			"fa-usb" ,
			"fa-usd" ,
			"fa-promo" ,
			"fa-promo-circle" ,
			"fa-promo-circle-o" ,
			"fa-promo-md" ,
			"fa-promo-o" ,
			"fa-promo-plus" ,
			"fa-promo-secret" ,
			"fa-promo-times" ,
			"fa-promos" ,
			"fa-venus" ,
			"fa-venus-double" ,
			"fa-venus-mars" ,
			"fa-viacoin" ,
			"fa-viadeo" ,
			"fa-viadeo-square" ,
			"fa-video-camera" ,
			"fa-vimeo" ,
			"fa-vimeo-square" ,
			"fa-vine" ,
			"fa-vk" ,
			"fa-volume-control-phone" ,
			"fa-volume-down" ,
			"fa-volume-off" ,
			"fa-volume-up" ,
			"fa-weibo" ,
			"fa-weixin" ,
			"fa-whatsapp" ,
			"fa-wheelchair" ,
			"fa-wheelchair-alt" ,
			"fa-wifi" ,
			"fa-wikipedia-w" ,
			"fa-window-close" ,
			"fa-window-close-o" ,
			"fa-window-maximize" ,
			"fa-window-minimize" ,
			"fa-window-restore" ,
			"fa-windows" ,
			"fa-wordpress" ,
			"fa-wpbeginner" ,
			"fa-wpexplorer" ,
			"fa-wpforms" ,
			"fa-wrench" ,
			"fa-xing" ,
			"fa-xing-square" ,
			"fa-y-combinator" ,
			"fa-yahoo" ,
			"fa-yelp" ,
			"fa-yoast" ,
			"fa-youtube" ,
			"fa-youtube-play" ,
			"fa-youtube-square"
		);
	}
	
	function faTest()
	{
		
		return array(
			'fa-glass'                               => 'f000' ,
			'fa-music'                               => 'f001' ,
			'fa-search'                              => 'f002' ,
			'fa-envelope-o'                          => 'f003' ,
			'fa-heart'                               => 'f004' ,
			'fa-star'                                => 'f005' ,
			'fa-star-o'                              => 'f006' ,
			'fa-promo'                               => 'f007' ,
			'fa-film'                                => 'f008' ,
			'fa-th-large'                            => 'f009' ,
			'fa-th'                                  => 'f00a' ,
			'fa-th-list'                             => 'f00b' ,
			'fa-check'                               => 'f00c' ,
			'fa-times'                               => 'f00d' ,
			'fa-search-plus'                         => 'f00e' ,
			'fa-search-minus'                        => 'f010' ,
			'fa-power-off'                           => 'f011' ,
			'fa-signal'                              => 'f012' ,
			'fa-cog'                                 => 'f013' ,
			'fa-trash-o'                             => 'f014' ,
			'fa-home'                                => 'f015' ,
			'fa-file-o'                              => 'f016' ,
			'fa-clock-o'                             => 'f017' ,
			'fa-road'                                => 'f018' ,
			'fa-download'                            => 'f019' ,
			'fa-arrow-circle-o-down'                 => 'f01a' ,
			'fa-arrow-circle-o-up'                   => 'f01b' ,
			'fa-inbox'                               => 'f01c' ,
			'fa-play-circle-o'                       => 'f01d' ,
			'fa-repeat'                              => 'f01e' ,
			'fa-refresh'                             => 'f021' ,
			'fa-list-alt'                            => 'f022' ,
			'fa-lock'                                => 'f023' ,
			'fa-flag'                                => 'f024' ,
			'fa-headphones'                          => 'f025' ,
			'fa-volume-off'                          => 'f026' ,
			'fa-volume-down'                         => 'f027' ,
			'fa-volume-up'                           => 'f028' ,
			'fa-qrcode'                              => 'f029' ,
			'fa-barcode'                             => 'f02a' ,
			'fa-tag'                                 => 'f02b' ,
			'fa-tags'                                => 'f02c' ,
			'fa-book'                                => 'f02d' ,
			'fa-bookmark'                            => 'f02e' ,
			'fa-print'                               => 'f02f' ,
			'fa-camera'                              => 'f030' ,
			'fa-font'                                => 'f031' ,
			'fa-bold'                                => 'f032' ,
			'fa-italic'                              => 'f033' ,
			'fa-text-height'                         => 'f034' ,
			'fa-text-width'                          => 'f035' ,
			'fa-align-left'                          => 'f036' ,
			'fa-align-center'                        => 'f037' ,
			'fa-align-right'                         => 'f038' ,
			'fa-align-justify'                       => 'f039' ,
			'fa-list'                                => 'f03a' ,
			'fa-outdent'                             => 'f03b' ,
			'fa-indent'                              => 'f03c' ,
			'fa-video-camera'                        => 'f03d' ,
			'fa-picture-o'                           => 'f03e' ,
			'fa-pencil'                              => 'f040' ,
			'fa-map-marker'                          => 'f041' ,
			'fa-adjust'                              => 'f042' ,
			'fa-tint'                                => 'f043' ,
			'fa-pencil-square-o'                     => 'f044' ,
			'fa-share-square-o'                      => 'f045' ,
			'fa-check-square-o'                      => 'f046' ,
			'fa-arrows'                              => 'f047' ,
			'fa-step-backward'                       => 'f048' ,
			'fa-fast-backward'                       => 'f049' ,
			'fa-backward'                            => 'f04a' ,
			'fa-play'                                => 'f04b' ,
			'fa-pause'                               => 'f04c' ,
			'fa-stop'                                => 'f04d' ,
			'fa-forward'                             => 'f04e' ,
			'fa-fast-forward'                        => 'f050' ,
			'fa-step-forward'                        => 'f051' ,
			'fa-eject'                               => 'f052' ,
			'fa-chevron-left'                        => 'f053' ,
			'fa-chevron-right'                       => 'f054' ,
			'fa-plus-circle'                         => 'f055' ,
			'fa-minus-circle'                        => 'f056' ,
			'fa-times-circle'                        => 'f057' ,
			'fa-check-circle'                        => 'f058' ,
			'fa-question-circle'                     => 'f059' ,
			'fa-info-circle'                         => 'f05a' ,
			'fa-crosshairs'                          => 'f05b' ,
			'fa-times-circle-o'                      => 'f05c' ,
			'fa-check-circle-o'                      => 'f05d' ,
			'fa-ban'                                 => 'f05e' ,
			'fa-arrow-left'                          => 'f060' ,
			'fa-arrow-right'                         => 'f061' ,
			'fa-arrow-up'                            => 'f062' ,
			'fa-arrow-down'                          => 'f063' ,
			'fa-share'                               => 'f064' ,
			'fa-expand'                              => 'f065' ,
			'fa-compress'                            => 'f066' ,
			'fa-plus'                                => 'f067' ,
			'fa-minus'                               => 'f068' ,
			'fa-asterisk'                            => 'f069' ,
			'fa-exclamation-circle'                  => 'f06a' ,
			'fa-gift'                                => 'f06b' ,
			'fa-leaf'                                => 'f06c' ,
			'fa-fire'                                => 'f06d' ,
			'fa-eye'                                 => 'f06e' ,
			'fa-eye-slash'                           => 'f070' ,
			'fa-exclamation-triangle'                => 'f071' ,
			'fa-plane'                               => 'f072' ,
			'fa-calendar'                            => 'f073' ,
			'fa-random'                              => 'f074' ,
			'fa-comment'                             => 'f075' ,
			'fa-magnet'                              => 'f076' ,
			'fa-chevron-up'                          => 'f077' ,
			'fa-chevron-down'                        => 'f078' ,
			'fa-retweet'                             => 'f079' ,
			'fa-shopping-cart'                       => 'f07a' ,
			'fa-folder'                              => 'f07b' ,
			'fa-folder-open'                         => 'f07c' ,
			'fa-arrows-v'                            => 'f07d' ,
			'fa-arrows-h'                            => 'f07e' ,
			'fa-bar-chart'                           => 'f080' ,
			'fa-twitter-square'                      => 'f081' ,
			'fa-facebook-square'                     => 'f082' ,
			'fa-camera-retro'                        => 'f083' ,
			'fa-key'                                 => 'f084' ,
			'fa-cogs'                                => 'f085' ,
			'fa-comments'                            => 'f086' ,
			'fa-thumbs-o-up'                         => 'f087' ,
			'fa-thumbs-o-down'                       => 'f088' ,
			'fa-star-half'                           => 'f089' ,
			'fa-heart-o'                             => 'f08a' ,
			'fa-sign-out'                            => 'f08b' ,
			'fa-linkedin-square'                     => 'f08c' ,
			'fa-thumb-tack'                          => 'f08d' ,
			'fa-external-link'                       => 'f08e' ,
			'fa-sign-in'                             => 'f090' ,
			'fa-trophy'                              => 'f091' ,
			'fa-github-square'                       => 'f092' ,
			'fa-upload'                              => 'f093' ,
			'fa-lemon-o'                             => 'f094' ,
			'fa-phone'                               => 'f095' ,
			'fa-square-o'                            => 'f096' ,
			'fa-bookmark-o'                          => 'f097' ,
			'fa-phone-square'                        => 'f098' ,
			'fa-twitter'                             => 'f099' ,
			'fa-facebook'                            => 'f09a' ,
			'fa-github'                              => 'f09b' ,
			'fa-unlock'                              => 'f09c' ,
			'fa-credit-card'                         => 'f09d' ,
			'fa-rss'                                 => 'f09e' ,
			'fa-hdd-o'                               => 'f0a0' ,
			'fa-bullhorn'                            => 'f0a1' ,
			'fa-bell'                                => 'f0f3' ,
			'fa-certificate'                         => 'f0a3' ,
			'fa-hand-o-right'                        => 'f0a4' ,
			'fa-hand-o-left'                         => 'f0a5' ,
			'fa-hand-o-up'                           => 'f0a6' ,
			'fa-hand-o-down'                         => 'f0a7' ,
			'fa-arrow-circle-left'                   => 'f0a8' ,
			'fa-arrow-circle-right'                  => 'f0a9' ,
			'fa-arrow-circle-up'                     => 'f0aa' ,
			'fa-arrow-circle-down'                   => 'f0ab' ,
			'fa-globe'                               => 'f0ac' ,
			'fa-wrench'                              => 'f0ad' ,
			'fa-tasks'                               => 'f0ae' ,
			'fa-filter'                              => 'f0b0' ,
			'fa-briefcase'                           => 'f0b1' ,
			'fa-arrows-alt'                          => 'f0b2' ,
			'fa-promos'                              => 'f0c0' ,
			'fa-link'                                => 'f0c1' ,
			'fa-cloud'                               => 'f0c2' ,
			'fa-flask'                               => 'f0c3' ,
			'fa-scissors'                            => 'f0c4' ,
			'fa-files-o'                             => 'f0c5' ,
			'fa-paperclip'                           => 'f0c6' ,
			'fa-floppy-o'                            => 'f0c7' ,
			'fa-square'                              => 'f0c8' ,
			'fa-bars'                                => 'f0c9' ,
			'fa-list-ul'                             => 'f0ca' ,
			'fa-list-ol'                             => 'f0cb' ,
			'fa-strikethrough'                       => 'f0cc' ,
			'fa-underline'                           => 'f0cd' ,
			'fa-table'                               => 'f0ce' ,
			'fa-magic'                               => 'f0d0' ,
			'fa-truck'                               => 'f0d1' ,
			'fa-pinterest'                           => 'f0d2' ,
			'fa-pinterest-square'                    => 'f0d3' ,
			'fa-google-plus-square'                  => 'f0d4' ,
			'fa-google-plus'                         => 'f0d5' ,
			'fa-money'                               => 'f0d6' ,
			'fa-caret-down'                          => 'f0d7' ,
			'fa-caret-up'                            => 'f0d8' ,
			'fa-caret-left'                          => 'f0d9' ,
			'fa-caret-right'                         => 'f0da' ,
			'fa-columns'                             => 'f0db' ,
			'fa-sort'                                => 'f0dc' ,
			'fa-sort-desc'                           => 'f0dd' ,
			'fa-sort-asc'                            => 'f0de' ,
			'fa-envelope'                            => 'f0e0' ,
			'fa-linkedin'                            => 'f0e1' ,
			'fa-undo'                                => 'f0e2' ,
			'fa-gavel'                               => 'f0e3' ,
			'fa-tachometer'                          => 'f0e4' ,
			'fa-comment-o'                           => 'f0e5' ,
			'fa-comments-o'                          => 'f0e6' ,
			'fa-bolt'                                => 'f0e7' ,
			'fa-sitemap'                             => 'f0e8' ,
			'fa-umbrella'                            => 'f0e9' ,
			'fa-clipboard'                           => 'f0ea' ,
			'fa-lightbulb-o'                         => 'f0eb' ,
			'fa-exchange'                            => 'f0ec' ,
			'fa-cloud-download'                      => 'f0ed' ,
			'fa-cloud-upload'                        => 'f0ee' ,
			'fa-promo-md'                            => 'f0f0' ,
			'fa-stethoscope'                         => 'f0f1' ,
			'fa-suitcase'                            => 'f0f2' ,
			'fa-bell-o'                              => 'f0a2' ,
			'fa-coffee'                              => 'f0f4' ,
			'fa-cutlery'                             => 'f0f5' ,
			'fa-file-text-o'                         => 'f0f6' ,
			'fa-building-o'                          => 'f0f7' ,
			'fa-hospital-o'                          => 'f0f8' ,
			'fa-ambulance'                           => 'f0f9' ,
			'fa-medkit'                              => 'f0fa' ,
			'fa-fighter-jet'                         => 'f0fb' ,
			'fa-beer'                                => 'f0fc' ,
			'fa-h-square'                            => 'f0fd' ,
			'fa-plus-square'                         => 'f0fe' ,
			'fa-angle-double-left'                   => 'f100' ,
			'fa-angle-double-right'                  => 'f101' ,
			'fa-angle-double-up'                     => 'f102' ,
			'fa-angle-double-down'                   => 'f103' ,
			'fa-angle-left'                          => 'f104' ,
			'fa-angle-right'                         => 'f105' ,
			'fa-angle-up'                            => 'f106' ,
			'fa-angle-down'                          => 'f107' ,
			'fa-desktop'                             => 'f108' ,
			'fa-laptop'                              => 'f109' ,
			'fa-tablet'                              => 'f10a' ,
			'fa-mobile'                              => 'f10b' ,
			'fa-circle-o'                            => 'f10c' ,
			'fa-quote-left'                          => 'f10d' ,
			'fa-quote-right'                         => 'f10e' ,
			'fa-spinner'                             => 'f110' ,
			'fa-circle'                              => 'f111' ,
			'fa-reply'                               => 'f112' ,
			'fa-github-alt'                          => 'f113' ,
			'fa-folder-o'                            => 'f114' ,
			'fa-folder-open-o'                       => 'f115' ,
			'fa-smile-o'                             => 'f118' ,
			'fa-frown-o'                             => 'f119' ,
			'fa-meh-o'                               => 'f11a' ,
			'fa-gamepad'                             => 'f11b' ,
			'fa-keyboard-o'                          => 'f11c' ,
			'fa-flag-o'                              => 'f11d' ,
			'fa-flag-checkered'                      => 'f11e' ,
			'fa-terminal'                            => 'f120' ,
			'fa-code'                                => 'f121' ,
			'fa-reply-all'                           => 'f122' ,
			'fa-star-half-o'                         => 'f123' ,
			'fa-location-arrow'                      => 'f124' ,
			'fa-crop'                                => 'f125' ,
			'fa-code-fork'                           => 'f126' ,
			'fa-chain-broken'                        => 'f127' ,
			'fa-question'                            => 'f128' ,
			'fa-info'                                => 'f129' ,
			'fa-exclamation'                         => 'f12a' ,
			'fa-superscript'                         => 'f12b' ,
			'fa-subscript'                           => 'f12c' ,
			'fa-eraser'                              => 'f12d' ,
			'fa-puzzle-piece'                        => 'f12e' ,
			'fa-microphone'                          => 'f130' ,
			'fa-microphone-slash'                    => 'f131' ,
			'fa-shield'                              => 'f132' ,
			'fa-calendar-o'                          => 'f133' ,
			'fa-fire-extinguisher'                   => 'f134' ,
			'fa-rocket'                              => 'f135' ,
			'fa-maxcdn'                              => 'f136' ,
			'fa-chevron-circle-left'                 => 'f137' ,
			'fa-chevron-circle-right'                => 'f138' ,
			'fa-chevron-circle-up'                   => 'f139' ,
			'fa-chevron-circle-down'                 => 'f13a' ,
			'fa-html5'                               => 'f13b' ,
			'fa-css3'                                => 'f13c' ,
			'fa-anchor'                              => 'f13d' ,
			'fa-unlock-alt'                          => 'f13e' ,
			'fa-bullseye'                            => 'f140' ,
			'fa-ellipsis-h'                          => 'f141' ,
			'fa-ellipsis-v'                          => 'f142' ,
			'fa-rss-square'                          => 'f143' ,
			'fa-play-circle'                         => 'f144' ,
			'fa-ticket'                              => 'f145' ,
			'fa-minus-square'                        => 'f146' ,
			'fa-minus-square-o'                      => 'f147' ,
			'fa-level-up'                            => 'f148' ,
			'fa-level-down'                          => 'f149' ,
			'fa-check-square'                        => 'f14a' ,
			'fa-pencil-square'                       => 'f14b' ,
			'fa-external-link-square'                => 'f14c' ,
			'fa-share-square'                        => 'f14d' ,
			'fa-compass'                             => 'f14e' ,
			'fa-caret-square-o-down'                 => 'f150' ,
			'fa-caret-square-o-up'                   => 'f151' ,
			'fa-caret-square-o-right'                => 'f152' ,
			'fa-eur'                                 => 'f153' ,
			'fa-gbp'                                 => 'f154' ,
			'fa-usd'                                 => 'f155' ,
			'fa-inr'                                 => 'f156' ,
			'fa-jpy'                                 => 'f157' ,
			'fa-rub'                                 => 'f158' ,
			'fa-krw'                                 => 'f159' ,
			'fa-btc'                                 => 'f15a' ,
			'fa-file'                                => 'f15b' ,
			'fa-file-text'                           => 'f15c' ,
			'fa-sort-alpha-asc'                      => 'f15d' ,
			'fa-sort-alpha-desc'                     => 'f15e' ,
			'fa-sort-amount-asc'                     => 'f160' ,
			'fa-sort-amount-desc'                    => 'f161' ,
			'fa-sort-numeric-asc'                    => 'f162' ,
			'fa-sort-numeric-desc'                   => 'f163' ,
			'fa-thumbs-up'                           => 'f164' ,
			'fa-thumbs-down'                         => 'f165' ,
			'fa-youtube-square'                      => 'f166' ,
			'fa-youtube'                             => 'f167' ,
			'fa-xing'                                => 'f168' ,
			'fa-xing-square'                         => 'f169' ,
			'fa-youtube-play'                        => 'f16a' ,
			'fa-dropbox'                             => 'f16b' ,
			'fa-stack-overflow'                      => 'f16c' ,
			'fa-instagram'                           => 'f16d' ,
			'fa-flickr'                              => 'f16e' ,
			'fa-adn'                                 => 'f170' ,
			'fa-bitbucket'                           => 'f171' ,
			'fa-bitbucket-square'                    => 'f172' ,
			'fa-tumblr'                              => 'f173' ,
			'fa-tumblr-square'                       => 'f174' ,
			'fa-long-arrow-down'                     => 'f175' ,
			'fa-long-arrow-up'                       => 'f176' ,
			'fa-long-arrow-left'                     => 'f177' ,
			'fa-long-arrow-right'                    => 'f178' ,
			'fa-apple'                               => 'f179' ,
			'fa-windows'                             => 'f17a' ,
			'fa-android'                             => 'f17b' ,
			'fa-linux'                               => 'f17c' ,
			'fa-dribbble'                            => 'f17d' ,
			'fa-skype'                               => 'f17e' ,
			'fa-foursquare'                          => 'f180' ,
			'fa-trello'                              => 'f181' ,
			'fa-female'                              => 'f182' ,
			'fa-male'                                => 'f183' ,
			'fa-gratipay'                            => 'f184' ,
			'fa-sun-o'                               => 'f185' ,
			'fa-moon-o'                              => 'f186' ,
			'fa-archive'                             => 'f187' ,
			'fa-bug'                                 => 'f188' ,
			'fa-vk'                                  => 'f189' ,
			'fa-weibo'                               => 'f18a' ,
			'fa-renren'                              => 'f18b' ,
			'fa-pagelines'                           => 'f18c' ,
			'fa-stack-exchange'                      => 'f18d' ,
			'fa-arrow-circle-o-right'                => 'f18e' ,
			'fa-arrow-circle-o-left'                 => 'f190' ,
			'fa-caret-square-o-left'                 => 'f191' ,
			'fa-dot-circle-o'                        => 'f192' ,
			'fa-wheelchair'                          => 'f193' ,
			'fa-vimeo-square'                        => 'f194' ,
			'fa-try'                                 => 'f195' ,
			'fa-plus-square-o'                       => 'f196' ,
			'fa-space-shuttle'                       => 'f197' ,
			'fa-slack'                               => 'f198' ,
			'fa-envelope-square'                     => 'f199' ,
			'fa-wordpress'                           => 'f19a' ,
			'fa-openid'                              => 'f19b' ,
			'fa-university'                          => 'f19c' ,
			'fa-graduation-cap'                      => 'f19d' ,
			'fa-yahoo'                               => 'f19e' ,
			'fa-google'                              => 'f1a0' ,
			'fa-reddit'                              => 'f1a1' ,
			'fa-reddit-square'                       => 'f1a2' ,
			'fa-stumbleupon-circle'                  => 'f1a3' ,
			'fa-stumbleupon'                         => 'f1a4' ,
			'fa-delicious'                           => 'f1a5' ,
			'fa-digg'                                => 'f1a6' ,
			'fa-pied-piper-pp'                       => 'f1a7' ,
			'fa-pied-piper-alt'                      => 'f1a8' ,
			'fa-drupal'                              => 'f1a9' ,
			'fa-joomla'                              => 'f1aa' ,
			'fa-language'                            => 'f1ab' ,
			'fa-fax'                                 => 'f1ac' ,
			'fa-building'                            => 'f1ad' ,
			'fa-child'                               => 'f1ae' ,
			'fa-paw'                                 => 'f1b0' ,
			'fa-spoon'                               => 'f1b1' ,
			'fa-cube'                                => 'f1b2' ,
			'fa-cubes'                               => 'f1b3' ,
			'fa-behance'                             => 'f1b4' ,
			'fa-behance-square'                      => 'f1b5' ,
			'fa-steam'                               => 'f1b6' ,
			'fa-steam-square'                        => 'f1b7' ,
			'fa-recycle'                             => 'f1b8' ,
			'fa-car'                                 => 'f1b9' ,
			'fa-taxi'                                => 'f1ba' ,
			'fa-tree'                                => 'f1bb' ,
			'fa-spotify'                             => 'f1bc' ,
			'fa-deviantart'                          => 'f1bd' ,
			'fa-soundcloud'                          => 'f1be' ,
			'fa-database'                            => 'f1c0' ,
			'fa-file-pdf-o'                          => 'f1c1' ,
			'fa-file-word-o'                         => 'f1c2' ,
			'fa-file-excel-o'                        => 'f1c3' ,
			'fa-file-powerpoint-o'                   => 'f1c4' ,
			'fa-file-image-o'                        => 'f1c5' ,
			'fa-file-archive-o'                      => 'f1c6' ,
			'fa-file-audio-o'                        => 'f1c7' ,
			'fa-file-video-o'                        => 'f1c8' ,
			'fa-file-code-o'                         => 'f1c9' ,
			'fa-vine'                                => 'f1ca' ,
			'fa-codepen'                             => 'f1cb' ,
			'fa-jsfiddle'                            => 'f1cc' ,
			'fa-life-ring'                           => 'f1cd' ,
			'fa-circle-o-notch'                      => 'f1ce' ,
			'fa-rebel'                               => 'f1d0' ,
			'fa-empire'                              => 'f1d1' ,
			'fa-git-square'                          => 'f1d2' ,
			'fa-git'                                 => 'f1d3' ,
			'fa-hacker-news'                         => 'f1d4' ,
			'fa-tencent-weibo'                       => 'f1d5' ,
			'fa-qq'                                  => 'f1d6' ,
			'fa-weixin'                              => 'f1d7' ,
			'fa-paper-plane'                         => 'f1d8' ,
			'fa-paper-plane-o'                       => 'f1d9' ,
			'fa-history'                             => 'f1da' ,
			'fa-circle-thin'                         => 'f1db' ,
			'fa-header'                              => 'f1dc' ,
			'fa-paragraph'                           => 'f1dd' ,
			'fa-sliders'                             => 'f1de' ,
			'fa-share-alt'                           => 'f1e0' ,
			'fa-share-alt-square'                    => 'f1e1' ,
			'fa-bomb'                                => 'f1e2' ,
			'fa-futbol-o'                            => 'f1e3' ,
			'fa-tty'                                 => 'f1e4' ,
			'fa-binoculars'                          => 'f1e5' ,
			'fa-plug'                                => 'f1e6' ,
			'fa-slideshare'                          => 'f1e7' ,
			'fa-twitch'                              => 'f1e8' ,
			'fa-yelp'                                => 'f1e9' ,
			'fa-newspaper-o'                         => 'f1ea' ,
			'fa-wifi'                                => 'f1eb' ,
			'fa-calculator'                          => 'f1ec' ,
			'fa-paypal'                              => 'f1ed' ,
			'fa-google-wallet'                       => 'f1ee' ,
			'fa-cc-visa'                             => 'f1f0' ,
			'fa-cc-mastercard'                       => 'f1f1' ,
			'fa-cc-discover'                         => 'f1f2' ,
			'fa-cc-amex'                             => 'f1f3' ,
			'fa-cc-paypal'                           => 'f1f4' ,
			'fa-cc-stripe'                           => 'f1f5' ,
			'fa-bell-slash'                          => 'f1f6' ,
			'fa-bell-slash-o'                        => 'f1f7' ,
			'fa-trash'                               => 'f1f8' ,
			'fa-copyright'                           => 'f1f9' ,
			'fa-at'                                  => 'f1fa' ,
			'fa-eyedropper'                          => 'f1fb' ,
			'fa-paint-brush'                         => 'f1fc' ,
			'fa-birthday-cake'                       => 'f1fd' ,
			'fa-area-chart'                          => 'f1fe' ,
			'fa-pie-chart'                           => 'f200' ,
			'fa-line-chart'                          => 'f201' ,
			'fa-lastfm'                              => 'f202' ,
			'fa-lastfm-square'                       => 'f203' ,
			'fa-toggle-off'                          => 'f204' ,
			'fa-toggle-on'                           => 'f205' ,
			'fa-bicycle'                             => 'f206' ,
			'fa-bus'                                 => 'f207' ,
			'fa-ioxhost'                             => 'f208' ,
			'fa-angellist'                           => 'f209' ,
			'fa-cc'                                  => 'f20a' ,
			'fa-ils'                                 => 'f20b' ,
			'fa-meanpath'                            => 'f20c' ,
			'fa-buysellads'                          => 'f20d' ,
			'fa-connectdevelop'                      => 'f20e' ,
			'fa-dashcube'                            => 'f210' ,
			'fa-forumbee'                            => 'f211' ,
			'fa-leanpub'                             => 'f212' ,
			'fa-sellsy'                              => 'f213' ,
			'fa-shirtsinbulk'                        => 'f214' ,
			'fa-simplybuilt'                         => 'f215' ,
			'fa-skyatlas'                            => 'f216' ,
			'fa-cart-plus'                           => 'f217' ,
			'fa-cart-arrow-down'                     => 'f218' ,
			'fa-diamond'                             => 'f219' ,
			'fa-ship'                                => 'f21a' ,
			'fa-promo-secret'                        => 'f21b' ,
			'fa-motorcycle'                          => 'f21c' ,
			'fa-street-view'                         => 'f21d' ,
			'fa-heartbeat'                           => 'f21e' ,
			'fa-venus'                               => 'f221' ,
			'fa-mars'                                => 'f222' ,
			'fa-mercury'                             => 'f223' ,
			'fa-transgender'                         => 'f224' ,
			'fa-transgender-alt'                     => 'f225' ,
			'fa-venus-double'                        => 'f226' ,
			'fa-mars-double'                         => 'f227' ,
			'fa-venus-mars'                          => 'f228' ,
			'fa-mars-stroke'                         => 'f229' ,
			'fa-mars-stroke-v'                       => 'f22a' ,
			'fa-mars-stroke-h'                       => 'f22b' ,
			'fa-neuter'                              => 'f22c' ,
			'fa-genderless'                          => 'f22d' ,
			'fa-facebook-official'                   => 'f230' ,
			'fa-pinterest-p'                         => 'f231' ,
			'fa-whatsapp'                            => 'f232' ,
			'fa-server'                              => 'f233' ,
			'fa-promo-plus'                          => 'f234' ,
			'fa-promo-times'                         => 'f235' ,
			'fa-bed'                                 => 'f236' ,
			'fa-viacoin'                             => 'f237' ,
			'fa-train'                               => 'f238' ,
			'fa-subway'                              => 'f239' ,
			'fa-medium'                              => 'f23a' ,
			'fa-y-combinator'                        => 'f23b' ,
			'fa-optin-monster'                       => 'f23c' ,
			'fa-opencart'                            => 'f23d' ,
			'fa-expeditedssl'                        => 'f23e' ,
			'fa-battery-full'                        => 'f240' ,
			'fa-battery-three-quarters'              => 'f241' ,
			'fa-battery-half'                        => 'f242' ,
			'fa-battery-quarter'                     => 'f243' ,
			'fa-battery-empty'                       => 'f244' ,
			'fa-mouse-pointer'                       => 'f245' ,
			'fa-i-cursor'                            => 'f246' ,
			'fa-object-group'                        => 'f247' ,
			'fa-object-ungroup'                      => 'f248' ,
			'fa-sticky-note'                         => 'f249' ,
			'fa-sticky-note-o'                       => 'f24a' ,
			'fa-cc-jcb'                              => 'f24b' ,
			'fa-cc-diners-club'                      => 'f24c' ,
			'fa-clone'                               => 'f24d' ,
			'fa-balance-scale'                       => 'f24e' ,
			'fa-hourglass-o'                         => 'f250' ,
			'fa-hourglass-start'                     => 'f251' ,
			'fa-hourglass-half'                      => 'f252' ,
			'fa-hourglass-end'                       => 'f253' ,
			'fa-hourglass'                           => 'f254' ,
			'fa-hand-rock-o'                         => 'f255' ,
			'fa-hand-paper-o'                        => 'f256' ,
			'fa-hand-scissors-o'                     => 'f257' ,
			'fa-hand-lizard-o'                       => 'f258' ,
			'fa-hand-spock-o'                        => 'f259' ,
			'fa-hand-pointer-o'                      => 'f25a' ,
			'fa-hand-peace-o'                        => 'f25b' ,
			'fa-trademark'                           => 'f25c' ,
			'fa-registered'                          => 'f25d' ,
			'fa-creative-commons'                    => 'f25e' ,
			'fa-gg'                                  => 'f260' ,
			'fa-gg-circle'                           => 'f261' ,
			'fa-tripadvisor'                         => 'f262' ,
			'fa-odnoklassniki'                       => 'f263' ,
			'fa-odnoklassniki-square'                => 'f264' ,
			'fa-get-pocket'                          => 'f265' ,
			'fa-wikipedia-w'                         => 'f266' ,
			'fa-safari'                              => 'f267' ,
			'fa-chrome'                              => 'f268' ,
			'fa-firefox'                             => 'f269' ,
			'fa-opera'                               => 'f26a' ,
			'fa-internet-explorer'                   => 'f26b' ,
			'fa-television'                          => 'f26c' ,
			'fa-contao'                              => 'f26d' ,
			'fa-500px'                               => 'f26e' ,
			'fa-amazon'                              => 'f270' ,
			'fa-calendar-plus-o'                     => 'f271' ,
			'fa-calendar-minus-o'                    => 'f272' ,
			'fa-calendar-times-o'                    => 'f273' ,
			'fa-calendar-check-o'                    => 'f274' ,
			'fa-industry'                            => 'f275' ,
			'fa-map-pin'                             => 'f276' ,
			'fa-map-signs'                           => 'f277' ,
			'fa-map-o'                               => 'f278' ,
			'fa-map'                                 => 'f279' ,
			'fa-commenting'                          => 'f27a' ,
			'fa-commenting-o'                        => 'f27b' ,
			'fa-houzz'                               => 'f27c' ,
			'fa-vimeo'                               => 'f27d' ,
			'fa-black-tie'                           => 'f27e' ,
			'fa-fonticons'                           => 'f280' ,
			'fa-reddit-alien'                        => 'f281' ,
			'fa-edge'                                => 'f282' ,
			'fa-credit-card-alt'                     => 'f283' ,
			'fa-codiepie'                            => 'f284' ,
			'fa-modx'                                => 'f285' ,
			'fa-fort-awesome'                        => 'f286' ,
			'fa-usb'                                 => 'f287' ,
			'fa-product-hunt'                        => 'f288' ,
			'fa-mixcloud'                            => 'f289' ,
			'fa-scribd'                              => 'f28a' ,
			'fa-pause-circle'                        => 'f28b' ,
			'fa-pause-circle-o'                      => 'f28c' ,
			'fa-stop-circle'                         => 'f28d' ,
			'fa-stop-circle-o'                       => 'f28e' ,
			'fa-shopping-bag'                        => 'f290' ,
			'fa-shopping-basket'                     => 'f291' ,
			'fa-hashtag'                             => 'f292' ,
			'fa-bluetooth'                           => 'f293' ,
			'fa-bluetooth-b'                         => 'f294' ,
			'fa-percent'                             => 'f295' ,
			'fa-gitlab'                              => 'f296' ,
			'fa-wpbeginner'                          => 'f297' ,
			'fa-wpforms'                             => 'f298' ,
			'fa-envira'                              => 'f299' ,
			'fa-universal-access'                    => 'f29a' ,
			'fa-wheelchair-alt'                      => 'f29b' ,
			'fa-question-circle-o'                   => 'f29c' ,
			'fa-blind'                               => 'f29d' ,
			'fa-audio-description'                   => 'f29e' ,
			'fa-volume-control-phone'                => 'f2a0' ,
			'fa-braille'                             => 'f2a1' ,
			'fa-assistive-listening-systems'         => 'f2a2' ,
			'fa-american-sign-language-interpreting' => 'f2a3' ,
			'fa-deaf'                                => 'f2a4' ,
			'fa-glide'                               => 'f2a5' ,
			'fa-glide-g'                             => 'f2a6' ,
			'fa-sign-language'                       => 'f2a7' ,
			'fa-low-vision'                          => 'f2a8' ,
			'fa-viadeo'                              => 'f2a9' ,
			'fa-viadeo-square'                       => 'f2aa' ,
			'fa-snapchat'                            => 'f2ab' ,
			'fa-snapchat-ghost'                      => 'f2ac' ,
			'fa-snapchat-square'                     => 'f2ad' ,
			'fa-pied-piper'                          => 'f2ae' ,
			'fa-first-order'                         => 'f2b0' ,
			'fa-yoast'                               => 'f2b1' ,
			'fa-themeisle'                           => 'f2b2' ,
			'fa-google-plus-official'                => 'f2b3' ,
			'fa-font-awesome'                        => 'f2b4'
		);
	}
	
	function sca_get_logo(){
		return ASSETS_IMAGES_PATH_URL . 'logo.jpg';
	}
	